### ISSUE TITLE
EVC USA Patching Error - ConsoleID mismatch.

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/RiiConnect24-Patcher#1]
This error prohibits installing USA region of patched Everybody Votes Channel.

We're working on a fix but any help would be appreciated.

![Error](https://cdn.discordapp.com/attachments/455533314259025920/455547182225948682/JPEG_20180610_214143.jpg)

**Comment by ApfelTV** [comment]
Its an Ticket error, we need to patch cetk and the ticket.

**Comment by ApfelTV** [comment]
So we need to remove the ConsoleID?

**Comment by Brawl345** [comment]
Yes

**Comment by ApfelTV** [comment]
Good to hear. Thanks!

**Comment by ApfelTV** [comment]
We are working on a patch, so i will close this issue.

**Comment by KcrPL** [comment]
No, close issues when issues are gone :P

**Comment by ApfelTV** [comment]
uhm, but we are working on a patch, and that patch will be release after we got it working, so it makes no sense to have one.

**Comment by KcrPL** [comment]
After we got it working, we close the issue. That's how it works

**Comment by Brawl345** [comment]
Yes it makes sense.... you close the issue via a commit.

**Comment by KcrPL** [comment]
@Brawl345, could you please contact me on Discord regarding this issue?

**Comment by KcrPL** [comment]
Fixed in [`8e31ee7`](https://github.com/KcrPL/KcrPL.github.io/commit/8e31ee7b21bb9c7b1b397afcb4f4e1defbad2492)
