### ISSUE TITLE
Why does the patcher don't patch my Wii games with wiimmfi ?

### ISSUE THREAD

**Issue by JustAJad** [RiiConnect24/RiiConnect24-Patcher#100]
This is really frustrating. I did everything they said, like putting the game in the same folder as the script and also as the `rc24.sh-files`. This is a big problem since am a beginner. Can please someone help me ! Here is the photo. And am never gonna close this page since It needs to help everyone
<img width="1143" alt="Capture d’écran 2021-12-12 à 16 22 36" src="https://user-images.githubusercontent.com/92444843/145718658-be60ecc2-1828-4d47-8c85-705b04c8d97a.png">
.

**Comment by SketchMaster2001** [comment]
On the screen right before it launches the patcher, it very clearly says `Make sure the WAD is in
the "rc24.sh-files" directory.`

<img width="762" alt="Screen Shot 2021-12-12 at 11 40 54 AM" src="https://user-images.githubusercontent.com/75850871/145721143-f56b8535-3674-47af-beac-de03183df6f9.png">

**Comment by JustAJad** [comment]
> On the screen right before it launches the patcher, it very clearly says `Make sure the WAD is in the "rc24.sh-files" directory.`
> 
> <img alt="Screen Shot 2021-12-12 at 11 40 54 AM" width="762" src="https://user-images.githubusercontent.com/75850871/145721143-f56b8535-3674-47af-beac-de03183df6f9.png">

But It DID NOT work ! That's what I need like help.

**Comment by JustAJad** [comment]
But dude. It's not even wad am talking about. Am talking about Wii games.

**Comment by SketchMaster2001** [comment]
First of all, read my comment again. Secondly, in the image you supplied, the WBFS is not in the `rc24.sh-files` directory

**Comment by JustAJad** [comment]
Well, It is on it.

**Comment by SketchMaster2001** [comment]
It is not

**Comment by JustAJad** [comment]
Let me give you a photo. But please help me for that.

**Comment by JustAJad** [comment]
<img width="701" alt="Capture d’écran 2021-12-12 à 17 47 38" src="https://user-images.githubusercontent.com/92444843/145721402-8241d48c-f88f-4703-8965-e96c680181b9.png">
I did it on it. But I did all of this on my USB. Tell me what should I do.

**Comment by TheShadowEevee** [comment]
You tried to run 2 different patchers, that second image is the Wad patcher. That isn't your only issue but please make sure you only run the iso/wbfs patcher while figuring this out since you are patching a wbfs game.

**Comment by SketchMaster2001** [comment]
You need to put in this directory

<img width="702" alt="Screen Shot 2021-12-12 at 11 49 58 AM" src="https://user-images.githubusercontent.com/75850871/145721481-3f7efb9b-6218-4b04-a8eb-a611a089e4c4.png">

**Comment by JustAJad** [comment]
Both ?

**Comment by SketchMaster2001** [comment]
The green one only

**Comment by KcrPL** [comment]
You're clearly misunderstanding the concept of working directory and a parent directory. 

The issue is invalid. Closing.

**Comment by JustAJad** [comment]
Ok. Then after that. I run the patcher ?

**Comment by JustAJad** [comment]
> You're clearly misunderstanding the concept of working directory and a parent directory.
> 
> The issue is invalid. Closing.

Wait ! I need help !

**Comment by JustAJad** [comment]
Am noob at this, really. It's the first time I hacked my Wii so It's hard for me.

**Comment by KcrPL** [comment]
This is not a support page. 

In order to get help, please contact us at support[at]riiconnect24.net or please join our Discord channel for further support.

**Comment by JustAJad** [comment]
Hello ?
