### ISSUE TITLE
"Riiconnect24 servers currently offline"

### ISSUE THREAD

**Issue by kittyguy14** [RiiConnect24/RiiConnect24-Patcher#102]
Every single time, without fail, when I press 1 to start the patcher, it says:
"Warning.
Riiconnect24 servers are currently offline.
It seems you have an active internet connection but Riiconnect24 servers are unavailable.
Please try again later!
Press any key to exit."
I am unable to provide a screenshot because I am currently on my Chromebook.

**Comment by KcrPL** [comment]
Hey,

Does this still happen?
