### ISSUE TITLE
Curl error with Unix patcher

### ISSUE THREAD

**Issue by MiaMG46** [RiiConnect24/RiiConnect24-Patcher#104]
When I try to run the Unix patcher with Linux Debian, it returns the following error:

An error has occurred.

ERROR DETAILS:
        * Task: 
        * Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://sketchmaster2001.github.io/RC24_Patcher/${1}
        * Line: 43
        * Exit code: 23

When I try to access the url it gives me a 404 error, so I'm thinking the issue is with the url? I have curl installed, so that's not the issue.

**Comment by KcrPL** [comment]
Run the script as root and try again.

**Comment by MiaMG46** [comment]
Sweet, it worked! Thanks
