### ISSUE TITLE
The progress gets stuck on 40% when I'm patching, on my PC (Acer Aspire 4743z/4437)

### ISSUE THREAD

**Issue by MisterAcro** [RiiConnect24/RiiConnect24-Patcher#107]

**Comment by MisterAcro** [comment]
Tomorrow I'll give a screenshot.

**Comment by larsenv** [comment]
That's because Nintendo's servers are currently down. Please join our Discord in the meantime: https://discord.gg/rc24

**Comment by MisterAcro** [comment]
When I will patch all of those channels? I really want.😭

**Comment by larsenv** [comment]
I have a solution, but you will need to join our Discord server or email support@riiconnect24.net for it.

**Comment by MisterAcro** [comment]
> I have a solution, but you will need to join our Discord server or email support@riiconnect24.net for it.

Thanks, I'm in (If you want to know who am I, I'm Teen ∆cro)
