### ISSUE TITLE
Error: Line 84 Exit code 4 on Unix Patcher

### ISSUE THREAD

**Issue by AdultShawarma** [RiiConnect24/RiiConnect24-Patcher#108]
Hey I got an error and it said to post it here. I've used this program an different SD card on the same OS and had no problems. I am using the latest version. OS: Pop!_OS 21.10 (Linux)

ERROR DETAILS:
	* Task: 
	* Command: ./Sharpii nusd -id ${2}${region_hex} -v ${3} -o Temp/Working/${1} -wad -q
	* Line: 84
	* Exit code: 4

**Comment by TheShadowEevee** [comment]
The server that hosts the files is currently down. Please see https://status.rc24.xyz/ for updates. 

The patcher will be updated soon to better explain the issue when there's a server problem, Thank you!
