### ISSUE TITLE
RiiConnect24 1.4.4 - NUS 

### ISSUE THREAD

**Issue by k0rAy1o01** [RiiConnect24/RiiConnect24-Patcher#109]
So I've tried to use the newest Version of the patcher, and it doesn't work. 
It fails right after selecting the device saying the patcher needs the Nintendo Update Servers/NUS and it might be under maintance.
Now Version 1.4.3 works in that regard. 

System Specs (if needed):

Windows 11
Ryzen 7 2700x
32gb Ram

**Comment by larsenv** [comment]
I have a solution, but you will need to join our Discord server or email support@riiconnect24.net for it.

**Comment by KcrPL** [comment]
RiIConnect24 Patcher v1.4.3 has broken NUS detection. It will still fail while patching.

**Comment by KcrPL** [comment]
*Resolved in update v1.4.5*
