### ISSUE TITLE
The program goes into a loop (1.4.5)

### ISSUE THREAD

**Issue by DCG42** [RiiConnect24/RiiConnect24-Patcher#110]
The program after patching the IOS, at 55% a message pops up saying that Visual C++ is not installed, the program installs it if it is run as administrator, but after installing it restarts and when it reaches 55% the same message appears again. Restarting has not solved anything and installing it manually has not solved anything either.
![image](https://user-images.githubusercontent.com/101950828/159138032-7eefd9c1-61ac-4d76-a134-c59e90bd72ee.png)

**Comment by KcrPL** [comment]
Can you please enter settings and tell me what's your reporting ID?

**Comment by franciscourzuagithub** [comment]
Been having the same loop issue. Here is my reporting ID if it can help: uQh5JJ

**Comment by KcrPL** [comment]
Can you please open RiiConnect24 Patcher, go into settings and switch to the BETA version of it?
Let me know if it fixed the issue you were having.
