### ISSUE TITLE
RC24-Patcher Issue

### ISSUE THREAD

**Issue by IntoTheSnakePit** [RiiConnect24/RiiConnect24-Patcher#116]
ERROR DETAILS:
        * Task: 
        * Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure https://sketchmaster2001.github.io/RC24_Patcher/${1}
        * Line: 43
        * Exit code: 23

**Comment by FilippoBellei** [comment]
Same for me on Fedora 36.

**Comment by KcrPL** [comment]
`CURLE_WRITE_ERROR (23)`

Move the script to a location where you have write permissions or fix the permissions.
