### ISSUE TITLE
UNIX Error Line 61, exit code: 137

### ISSUE THREAD

**Issue by joeandwatson** [RiiConnect24/RiiConnect24-Patcher#119]
An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: ./Sharpii nusd -ios ${1} -v ${2} -o 
Temp/Working/Wii/IOS${1}/Temp.wad -wad -q
	* Line: 61
	* Exit code: 137

**Comment by theshillito** [comment]
Yep, I've been getting the same error.
```
An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: ./Sharpii nusd -ios ${1} -v ${2} -o 
Temp/Working/Wii/IOS${1}/Temp.wad -wad -q
	* Line: 61
	* Exit code: 137
```
This is on macOS 12.5.1 (Monterey) on an Apple Silicon (M1 Pro) Mac with or without an SD card connected and with or without sudo privilages and in zsh or bash.

It creates the folder mentioned in the error as in the picture below but doesn't get to making Temp.wad.

<img width="772" alt="Screenshot 2022-08-25 at 12 15 41" src="https://user-images.githubusercontent.com/1828418/186650494-03d1b327-6122-4904-896c-b8a272dc64f7.png">
