### ISSUE TITLE
Curl errors after starting the patcher

### ISSUE THREAD

**Issue by just-a-squid** [RiiConnect24/RiiConnect24-Patcher#120]
I originally got an error after attempting to start the patcher saying there was an error downloading curl. After following the instructions to fix it I got these new errors upon pressing start saying “curl: <23> Failed writing body <0 != 200>“ and “curl: <6> Could not resolve host:”. This always crashes the patcher. Not sure if it’s related to the first error and no idea what to do to fix.
![image](https://user-images.githubusercontent.com/112289658/187052444-8a758565-5332-41e4-9ec7-8cf113955a6f.png)
![image](https://user-images.githubusercontent.com/112289658/187052455-9da9d212-8fec-4ce0-a5d0-f85670561f5b.png)

**Comment by KcrPL** [comment]
Can you try using it on Windows 10 or 11 and let me know if it works on it?

**Comment by ImBadAtOsu7** [comment]
i have the same error on windows 10

**Comment by KcrPL** [comment]
What Windows 10 version are you on? (Please check by running `winver` and check the build number (` will be 10.XXXXX.XXXX`)
