### ISSUE TITLE
failed macos installation

### ISSUE THREAD

**Issue by danaa4000** [RiiConnect24/RiiConnect24-Patcher#121]
After I answer the question "What region is your device from", it shows an error
<img width="324" alt="image" src="https://user-images.githubusercontent.com/79311143/188746645-6a964272-939d-401e-b8c4-e0912a853a20.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/79311143/188746703-6fc56d2a-5d90-47a3-a0bd-b07967118411.png">

**Comment by larsenv** [comment]
Please email support@riiconnect24.net.

**Comment by Lipooooo** [comment]
how to you run it???? i type all the command in the terminal chmod +x etc.... i have the error no such file or directory after the commande ./riiconnect24...

**Comment by TheShadowEevee** [comment]
Closing as resolved as support was offered over email. If this issue reoccurs feel free to reopen this issue with more details, anyone else is free to create a new issue.
