### ISSUE TITLE
Linux - Error line 43

### ISSUE THREAD

**Issue by LinUwUxCat** [RiiConnect24/RiiConnect24-Patcher#125]
Heya, running the patcher, i get 
```
An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure https://sketchmaster2001.github.io/RC24_Patcher/${1}
	* Line: 43
	* Exit code: 22
```
There seems to be a lot of issues regarding the patcher and unix, is it even still updated?

**Comment by Penglyn** [comment]
Same issue here

**Comment by Penglyn** [comment]
I have found the issue, and will be making a pull request to fix this.

**Comment by KcrPL** [comment]
The hosting will be moved to our server.
