### ISSUE TITLE
UNIX patcher download URL is down

### ISSUE THREAD

**Issue by Thesola10** [RiiConnect24/RiiConnect24-Patcher#127]
The Unix/Linux version of the RC24 patcher refers to an address, https://sketchmaster2001.GitHub.io , to download certain files, but the associated GitHub account doesn't appear to exist anymore. 

This renders the patcher unusable in its current state.

**Comment by Penglyn** [comment]
This is a known issue, and is being fixed by KcrPL as we speak

**Comment by KcrPL** [comment]
Fixed in 57fd2021c4a93348b9e9faf6affff4e23f9ace3d
