### ISSUE TITLE
Unix patcher crashes with exit code 134 when running Sharpii

### ISSUE THREAD

**Issue by pokefan9830** [RiiConnect24/RiiConnect24-Patcher#128]

**Comment by TheShadowEevee** [comment]
I changed the title no make everything easier to read, the previous title was the below error.
`An error has occurred.  ERROR DETAILS:     
* Task:      
* Command: ./Sharpii nusd -ios ${1} -v ${2} -o Temp/Working/Wii/IOS${1}/Temp.wad -wad -q     
* Line: 78     
* Exit code: 134`

**Comment by pokefan9830** [comment]
thx

**Comment by Alriceee** [comment]
The same thing just happened to me, I think it's something to do with linux itself.

**Comment by pokefan9830** [comment]
thanks thoute it might be my computer Itself

**Comment by TheShadowEevee** [comment]
@pokefan9830 @Alriceee Are either of you still having this issue? If you are, what OS and Version are you running?

I'm changing the title back to what it was previously for now; Issue titles are designed to be quick, at-a-glance information for those reviewing issues. If you have questions about this please let me know!

**Comment by Alriceee** [comment]
> @pokefan9830 @Alriceee Are either of you still having this issue? If you are, what OS and Version are you running?
> 
> I'm changing the title back to what it was previously for now; Issue titles are designed to be quick, at-a-glance information for those reviewing issues. If you have questions about this please let me know!

I haven't tried again in awhile, but i was running the latest version of RiiConnect24-Patcher, and my os was ubuntu 22.04
