### ISSUE TITLE
Mac error line: 76 exit code: 4

### ISSUE THREAD

**Issue by Boboboey** [RiiConnect24/RiiConnect24-Patcher#133]
ERROR DETAILS:
	* Task: 
	* Command: ./Sharpii wad -p Temp/Working/Wii/IOS${1} 
"${out_path}/WAD/IOS${1} (RiiConnect24).wad" -f -q
	* Line: 76
	* Exit code: 4

**Comment by KcrPL** [comment]
To get help with this error, please join our Discord server. The issues page is reserved for reporting bugs and issues with the patcher, not the errors that you encounter during the patching process.
