### ISSUE TITLE
[Enhacement] Wii homebrew version of the Patcher

### ISSUE THREAD

**Issue by DraconicNEO** [RiiConnect24/RiiConnect24-Patcher#135]
I think it would be a good idea to have an on Wii patcher (either as an installable wad or Homebrew app) similar to what WiiLink has for their service since it would allow much easier updating of installed RC24 patches on the system itself.

**Comment by KcrPL** [comment]
No, it will literally take 20 minutes to do everything on the Wii - Wii's networking is really bad. It will be difficult and won't be convenient for the user at all.

It's been discussed before, we're staying with the patchers on PC.

**Comment by noahpistilli** [comment]
I am planning on deprecating mine as well, the Wii patcher is simply way too slow to be viable.
