### ISSUE TITLE
Any chance of getting Wii Mail working in Dolphin?

### ISSUE THREAD

**Issue by eisnerguy1** [RiiConnect24/RiiConnect24-Patcher#136]
So, I've got RiiConnect24 set up in Dolphin. I've been wanting to play the "Pokémon Adventure Squad" WiiWare games. In order to rescue Mew, Darkrai, Jirachi and Palkia, Wii Mail needs to function. Has there been any progress in getting Wii Mail working in Dolphin?

![0000000100000002_2023-01-22_22-08-46](https://user-images.githubusercontent.com/3295271/214197413-1b4b0999-e327-4f70-961a-cbaa0365529a.png)

**Comment by larsenv** [comment]
In the future it will be supported hopefully.
