### ISSUE TITLE
How to Fix "fast_travel_(insert Number Here)" Error?

### ISSUE THREAD

**Issue by captainbob32** [RiiConnect24/RiiConnect24-Patcher#137]
I Was Using the Patcher and Moved it to the Desktop, then Open the Patcher. I Was Going to Install RC24 into Dolphin. Everything is Going Fine, But Something Flash Through the Pacther Screen, and I Used Bandicam to Record What it Was. It Said "cannot find fast_travel_(Insert number here)", and I Want to Fix this Error.

**Comment by KcrPL** [comment]
It is normal and expected. You can ignore it.

**Comment by captainbob32** [comment]
Oh! I'm Sorry about That. I Will Never Make an Issue This Stupid again.
