### ISSUE TITLE
"RiiConnect24 Patcher Unix ${ver}" --insecure 

### ISSUE THREAD

**Issue by Greyson1103** [RiiConnect24/RiiConnect24-Patcher#139]
ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --user-agent 
"RiiConnect24 Patcher Unix ${ver}" --insecure 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher_Unix/v1/${1}
	* Line: 56
	* Exit code: 23

**Comment by TheShadowEevee** [comment]
Exit code 23 from cURL is a Write error. Please make sure you have enough space on your device, and try making a new folder in your home directory and move the patcher there to make sure it has write permissions to it's directory. After doing both of these steps, try running the patcher again!

**Comment by Greyson1103** [comment]
Thanks!
