### ISSUE TITLE
Sharpii's -ios option is invalid on Windows with Turkish language support

### ISSUE THREAD

**Issue by linuxgemini** [RiiConnect24/RiiConnect24-Patcher#14]
The patcher always stopped at 34 percent.

Checking the line `move /y IOSPatcher\IOS31\00000006.app IOSPatcher\00000006.app` showed that the folder necessary (IOS31\\) was missing. 

To unpack the .app's, you need to have the .wad files, those were missing as well.

After manually checking IOSPatcher Sharpii commands, this happened:

```
C:\Users\linuxgemini\somefolder>IOSPatcher\Sharpii.exe NUSD -ios 80 -v latest -o IOSPatcher\IOS80-old.wad -wad
ERROR: No ID specified
```

The letter `i` has a different characteristic on Windows-1254, the upper-case state is `İ` instead of the traditional `I`. So I tried using `ı` where the upper-case state is the traditional `I` and: 

```
C:\Users\linuxgemini\somefolder>IOSPatcher\Sharpii.exe NUSD -ıos 80 -v latest -o IOSPatcher\IOS80-old.wad -wad
Downloading title...Done!
Operation completed succesfully!
```

Replacing the `-ios` flag on Sharpii commands with `-IOS` fixes this issue.

```
C:\Users\linuxgemini\somefolder>IOSPatcher\Sharpii.exe NUSD -IOS 80 -v latest -o IOSPatcher\IOS80-old.wad -wad
Downloading title...Done!
Operation completed succesfully!
```

**Comment by KcrPL** [comment]
Thank you for reporting this issue. It will be fixed in the next release.

**Comment by KcrPL** [comment]
Hopefully fixed in [`c59e0fe`](https://github.com/RiiConnect24/RiiConnect24-Patcher/commit/c59e0fe0d46bff69f7a14788c7fd31384f078dc6).

Check it and let me know if it's fixed.

**Comment by linuxgemini** [comment]
Just confirmed that its now working. Thanks for the fix.

**Comment by KcrPL** [comment]
You're welcome! :)
