### ISSUE TITLE
UNIX Temp/Working/${1} -wad -q LINE: 98 Exit Code: 127

### ISSUE THREAD

**Issue by TheKingMeta** [RiiConnect24/RiiConnect24-Patcher#142]
ERROR DETAILS:
        * Task:
        * Command: ./Sharpii nusd -id ${2}${region_hex} -v ${3} -o
Temp/Working/${1} -wad -q
        * Line: 98                                                                          * Exit code: 127

**Comment by TheShadowEevee** [comment]
Exit Code 127 is the code for "Command Not Found", what OS are you using? It's possible there isn't a Sharpii build for it.

**Comment by TheKingMeta** [comment]
I am using Termux on Android, and installed all the required packages it needed to run the script

**Comment by TheShadowEevee** [comment]
Ah. Termux doesn't like the binaries I can make with dotnet, I would try a different device or in a proot OS. Sharpii will not work on base Termux.

**Comment by TheKingMeta** [comment]
After installing Debian XFCE, I am now getting Line: 98 Exit Code: 137
