### ISSUE TITLE
What do I do with WAD files?

### ISSUE THREAD

**Issue by xendyex** [RiiConnect24/RiiConnect24-Patcher#147]
I've got all the files, copied the copy to sd files to my sd. But, I HAVE NO IDEA what to do with the .wad files... Any help?

**Comment by Naim2000** [comment]
Did you forget about the guide you were just following

**Comment by TheShadowEevee** [comment]
Copy the Wad files to an SD card and follow the guide at https://wii.guide/riiconnect24 starting from "Section II - Installing WADs". If you need help past there, join the Discord server on the wii.guide website and ask in a support channel for further help.
