### ISSUE TITLE
Batch script failing due to line endings

### ISSUE THREAD

**Issue by saneki** [RiiConnect24/RiiConnect24-Patcher#15]
When trying to select "1. Automatic Guided Installation" the batch script would fail with errors:

```
'RiiConnect24' is not recognized as an internal or external command, operable program or batch file.
'-----------------------------------------------------------------------------------------------------------------------------' is not recognized as an internal or external command, operable program or batch file.
'.' is not recognized as an internal or external command, operable program or batch file.
'Hello' is not recognized as an internal or external command, operable program or batch file.
'.' is not recognized as an internal or external command, operable program or batch file.
'The' is not recognized as an internal or external command, operable program or batch file.
'The' is not recognized as an internal or external command, operable program or batch file.
'.' is not recognized as an internal or external command, operable program or batch file.
'But' is not recognized as an internal or external command, operable program or batch file.
'.' is not recognized as an internal or external command, operable program or batch file.
Everybody was unexpected at this time.
```

This error was from line 1191, `echo %header%`. Apparently batch decided to start treating echos differently starting at that line number, because when removing the previous `cls` it would run `echo %header%` successfully, but then fail on the next echo line with the same errors.

Changing the line endings from `LF` to `CR LF` fixes the issue. [Git for Windows](https://gitforwindows.org/) automatically converts line endings to `CR LF` on checkout, but when downloading from GitHub over HTTP (including on the [Releases](https://github.com/RiiConnect24/RiiConnect24-Patcher/releases) page) it doesn't have the proper line endings.

**Comment by larsenv** [comment]
Thanks for making a detailed issue, line breaks really piss me off.

@KcrPL Can you please take a look?

**Comment by KcrPL** [comment]
Of course! I'll check it later because I'm busy right now.

**Comment by KcrPL** [comment]
Actually I just released a silent update. Give it a try and close the issue if everything is ok ;)

**Comment by KcrPL** [comment]
Good.
