### ISSUE TITLE
riiconect24 patcher

### ISSUE THREAD

**Issue by costasto** [RiiConnect24/RiiConnect24-Patcher#152]
hi it seems that any version of reconect24 is crashing soon after i double click it on windows 10 the last working version without crash is 1.4.9/1.1.3 any newer is crashing soon after i double click it

**Comment by Naim2000** [comment]
The latest is [v1.5.2](https://github.com/RiiConnect24/RiiConnect24-Patcher/releases/tag/v1.5.2%2Fv1.2.0). By the way, have you tried setting your system language to English? Windows acts very stupid sometimes
