### ISSUE TITLE
Error code 109343

### ISSUE THREAD

**Issue by BrossBean** [RiiConnect24/RiiConnect24-Patcher#155]
Everybody Votes asks me to select region, and it then tells me I cannot connect to the internet.

Today and Tomorrow channel if fine and functional.

With the Internet Channel web pages load forever but never gives me an error.

Check Mii Out is fully functions EXCEPT for importing miis. It tells me "Because there is a problem with the Wii system memory, WiiConnect24 cannot be used. Return to the wii menu and follow instructions. Error code: 109343" (What instructions, lol?)

Nintendo Channel displays this: "The system file for Nintendo Channel is corrupted. After deleting the Nintendo Channel from the Data Management screen, please download the Nintendo Channel from the Wii Shop Channel again. If this message still appears, visit support.nintendo.com

I am using Ishiiruka-Dolphin (1136), do I have to switch to real Dolphin, and which version would I have to if this is the case?

Are there any settings involving the memory I have to change?

Also worth noting: when I was installing it asked me about the SD card, I do not have an SD card, and I also do not have the ability to use my real Wii (I have NO TVs or monitors with AV hookup), did I mess up the installation by not having an SD card? I didn't quite understand what it wanted me to do at that point in the installer, and since it let me finish the installation and the channels appeared, I figured I did it correctly.

**Comment by Naim2000** [comment]
Come back when you are using a normal version of dolphin, lmfao

**Comment by BrossBean** [comment]
> Come back when you are using a normal version of dolphin, lmfao

You could simply be polite and confirm that yes, the version matters. I stated I was aware my version could be an issue and asked for clarification and which version is recommended. I want to be thorough when I ask questions so other people searching for errors online can find it, because nobody else had posted that error code from what I've seen.
