### ISSUE TITLE
new error please help!!!!!!!

### ISSUE THREAD

**Issue by aidwoods** [RiiConnect24/RiiConnect24-Patcher#156]
So I was trying to install Wiimmfi patch and I got this error message. can someone please help me and figure out why I am getting this message. 

ERROR DETAILS:
	* Task: 
	* Command: ./patch-images.sh
	* Line: 178
	* Exit code: 127

**Comment by Naim2000** [comment]
[Wiimmfi ISO Patcher](https://wiimmfi.de/patcher/iso)

However I personally prefer the temporary patches:
+ Dolphin Emulator: [Wiimmfi Auto Patcher on Dolphin Emulator](https://Naim2000.github.io/guides/dolphin/wiimmfi-autopatcher)
+ Wii/Wii U: Just go into the game's settings in your USB loader and set `Private server` to `wiimmfi.de`
