### ISSUE TITLE
Error Line 178 MacOS Monterey

### ISSUE THREAD

**Issue by Cyaimz431** [RiiConnect24/RiiConnect24-Patcher#159]
An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: ./patch-images.sh
	* Line: 178
	* Exit code: 127

**Comment by Naim2000** [comment]
[Wiimmfi ISO Patcher @ wiimmfi.de](https://wiimmfi.de/patcher/iso)
Ideally you want to use literally any other patcher for Wiimmfi though, ISO patching is pretty redundant
