### ISSUE TITLE
Wii Mail on Vwii doesn't work, it keeps giving me error 102304

### ISSUE THREAD

**Issue by Armandprogame** [RiiConnect24/RiiConnect24-Patcher#161]
I tried all method but wii mail on vwii is not working, all rc24 service is working very well on wii u but the wii mail not

**Comment by KCRTR3** [comment]
repatch ios80 and try patching the nwc24.cfg again i guess, also why did u open an issue here if you already made a thread on the riiconnect24 server

**Comment by Armandprogame** [comment]
Is not change, i repatch the ios80 and  the nwc24.cfg but is not working

**Comment by KCRTR3** [comment]
idk what difference this would do but did u install d2x cIOS vwii

**Comment by Armandprogame** [comment]
yes all three Cios. I put Cios249 with ios56, Cios250 with ios57 and Cios251 with ios58

**Comment by KCRTR3** [comment]
beta vWii?

**Comment by Armandprogame** [comment]
No, I've followed the entire Wii guide

**Comment by Armandprogame** [comment]
Is all stable

**Comment by KCRTR3** [comment]
oh god, follow https://wiiu.guide/vwii-modding and come back when u installed the correct ones

**Comment by KCRTR3** [comment]
also props to github for not redirecting to wiiu.guide, copy the link and paste it in a new tab

**Comment by Armandprogame** [comment]
The vwii ios80 and the vwii cios 249, 250, and 251 I already have them, i installed homebrew channel with compact installer AND I HAVE ALL WII U MODDED

**Comment by Armandprogame** [comment]
okay at this point I have to reset the wii u, what happens if I reset the modification with the payloader loader, tiramisu and aroma installed?

**Comment by KCRTR3** [comment]
is your router 802.11b, 2.4gHz and DMZ enabled?

**Comment by KCRTR3** [comment]
> okay at this point I have to reset the wii u, what happens if I reset the modification with the payloader loader, tiramisu and aroma installed?

no dont do it lol

**Comment by Armandprogame** [comment]
The 802.11b specs is enabled but i have disabled the dmz

**Comment by Armandprogame** [comment]
And 2.4GHZ obviously

**Comment by KCRTR3** [comment]
1)enable DMZ
2)vwii doesnt support WPA2-PSK

**Comment by Armandprogame** [comment]
It support WPA2-PSK AES?

**Comment by Armandprogame** [comment]
I know the wii u and vwii not support WPA2-PSK TKIP

**Comment by KCRTR3** [comment]
> It support WPA2-PSK AES?

it probably doesnt

**Comment by Armandprogame** [comment]
Exuse, give me the port forwarding of wii mail service

**Comment by Armandprogame** [comment]
Pls

**Comment by Armandprogame** [comment]
I have wii u and wpa2 psk aes is supported in so

**Comment by Armandprogame** [comment]
And vwii too

**Comment by KCRTR3** [comment]
try an hotspot and see if that works, or try an internet app such as homebrew browser and see if that works

**Comment by Armandprogame** [comment]
Ok, wait i test
