### ISSUE TITLE
[Unix] Curl exits early with exit code 35

### ISSUE THREAD

**Issue by Wolfstar258** [RiiConnect24/RiiConnect24-Patcher#164]
I tried to install RiiConnect24 on my Mac (Catalina), but this error shows up everytime. Permission for Terminal to access Downloads is enabled, so I’m not sure what’s going on.

![image](https://github.com/RiiConnect24/RiiConnect24-Patcher/assets/116023966/639726e4-4555-4781-a28f-7b5d99dd5000)

**Comment by Meproi** [comment]
Having exact same issue on Mac M1 w/ Somona.

**Comment by Wolfstar258** [comment]
> Having exact same issue on Mac M1 w/ Somona.

At least now I know it isn't an outdated computer or operating system that's the problem.

**Comment by TheShadowEevee** [comment]
Reopening as unresolved

**Comment by Wolfstar258** [comment]
> Reopening as unresolved

So, what does this issue have to do with? How can it be resolved?
