### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by a-person-that-exists-123** [RiiConnect24/RiiConnect24-Patcher#165]
RROR DETAILS:
        * Task: 
        * Command: curl --create-dirs -f -k -L -o "${2}" -S -s --user-agent "RiiConnect24 
Patcher Unix ${ver}" --insecure 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher_Unix/v1/${1}
        * Line: 57
        * Exit code: 23

**Comment by a-person-that-exists-123** [comment]
I'm on Chromebook.

**Comment by larsenv** [comment]
Please email us at support@riiconnect24.net for help.

**Comment by Naim2000** [comment]
cURL error 23 -> Failed writing output to destination. Where are you running the script

**Comment by a-person-that-exists-123** [comment]
? what the github post guide said

**Comment by a-person-that-exists-123** [comment]
thats where

**Comment by a-person-that-exists-123** [comment]
OH, I know what you mean now, in terminal.

**Comment by a-person-that-exists-123** [comment]
Or if not, chmod +x RiiConnect24Patcher.sh, then, ./RiiConnect24Patcher.sh

.

**Comment by a-person-that-exists-123** [comment]
i also tried with sudo and it said:RiiConnect24 Patcher for Unix v1.2.0
By HTV04, SketchMaster2001, and TheShadowEevee

Now loading...

"xdelta3" command not found! Please install the "xdelta3" package using your package 
manager. idk wtf that means

**Comment by Naim2000** [comment]
> ? what the github post guide said

The directory

**Comment by applecuckoo** [comment]
> "xdelta3" command not found! Please install the "xdelta3" package using your package
manager.

@a-person-that-exists-123 Hi! If you're still here, you should be able to install the missing package by running `sudo apt-get install xdelta3` in the terminal. That should make the message go away and make the rest work.
