### ISSUE TITLE
Falsely Detecting Servers as offline.

### ISSUE THREAD

**Issue by ebuggingSam123** [RiiConnect24/RiiConnect24-Patcher#166]
I tried to boot up RiiConnect24 patcher but it said that the servers are offline. So I went [here](https://status.rc24.xyz), but the servers were online. What is going on?

I am on the windows version btw

**Comment by mattysayanneMods** [comment]
me too but on wii, my CIOS58 is not downloaded,the internet channel and fortune smiles on you(i think its called like this)channel
this is so easy but i think we cant bcuz we are on 2024 not 2007-2016
