### ISSUE TITLE
Installer stops at 37%

### ISSUE THREAD

**Issue by EmmettVA** [RiiConnect24/RiiConnect24-Patcher#171]
The installer stops at thirty-seven percent. Using Windows 11.
![Screenshot 2024-01-04 185137](https://github.com/RiiConnect24/RiiConnect24-Patcher/assets/155691634/6c3b29fb-fd68-4340-aa31-fe65be6885f3)

**Comment by Naim2000** [comment]
I would like to ask how long it's been stuck for but this patcher doesn't matter anymore becaaaause:
https://github.com/WiiLink24/WiiLink24-Patcher/releases/latest

**Comment by EmmettVA** [comment]
okay
