### ISSUE TITLE
UNIX error : Line 42 and exit code 7

### ISSUE THREAD

**Issue by Amine69z8** [RiiConnect24/RiiConnect24-Patcher#173]
I recently bought a Wii and downloaded the RiiConnect24 patcher on Mac and this is the error message it gives me:

	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://sketchmaster2001.github.io/RC24_Patcher/${1}
	* Line: 42
	* Exit code: 7

Could someone help me please ?

Thank you !

**Comment by Naim2000** [comment]
This patcher is deprecated.
Use the [RiiConnect24 + WiiLink](https://github.com/WiiLink24/WiiLink24-Patcher/releases/latest) patcher
