### ISSUE TITLE
Cant play Wiimmfi

### ISSUE THREAD

**Issue by fgjhge** [RiiConnect24/RiiConnect24-Patcher#174]
I saw a video a few weeks ago saying that you can play Wiimmfi without a NAND, i tried it and it said I needed a NAND, can someone help why???

**Comment by fgjhge** [comment]
![image](https://github.com/RiiConnect24/RiiConnect24-Patcher/assets/70024716/c3941685-bb86-454e-9662-8b5fbfb029be)

**Comment by Naim2000** [comment]
What?

**Comment by supermilkdude67** [comment]
> I saw a video a few weeks ago saying that you can play Wiimmfi without a NAND, i tried it and it said I needed a NAND, can someone help why???

You need to dump the nand from your real wii with BootMii and import it to Dolphin with Tools > Manage NAND > Import BootMii NAND Backup

Please note that you should backup your original Dolphin NAND if you have anything else (save files, channel games) on Dolphin, or else it'll try to merge the NAND and you'll just end up with a corrupted NAND.

Also, you'll need to wait a week for the Wiifimii servers to activate your NAND, for purposes of keeping hackers off their servers, that's also why you can't use a Dolphin NAND.

**Comment by korbosoft** [comment]
that is a completely different error

**Comment by korbosoft** [comment]
besides, we have nothing to do with wiimmfi

**Comment by supermilkdude67** [comment]
> that is a completely different error

I used the image so they'll know what to expect when they dump their wii nand to Dolphin
