### ISSUE TITLE
Linux EVCPatcher trouble

### ISSUE THREAD

**Issue by Pysis868** [RiiConnect24/RiiConnect24-Patcher#19]
Running manually for USA on Fedora:
```
RiiConnect24 Patcher - (C) KcrPL, (C) Larsenv, (C) ApfelTV v1.0.0-BugFix2 (Compiled on 2018/07/21 at 9:26PM)
---------------------------------------------------------------------------------------------------------------------------
 [*] Patching Everybody Votes Channel... this can take some time

EVCPatcher/dwn/nustool: line 1: 404:: command not found
mv: cannot stat ‘0001000148414a45/512/*’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000018’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000019’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000002’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000003’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000004’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000001a’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000001b’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000007’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000008’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000010’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000001c’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000000b’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000000c’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/0000001d’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/00000018’: No such file or directory
cp: cannot stat ‘EVCPatcher/dwn/0001000148414A45/512/tmd’: No such file or directory
xdelta3: file open failed: read: 0001000148414A45/512/00000001.app: No such file or directory
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
An unknown error occured, please try again

ERROR DETAILS: Array index is out of range.
Waiting...^C
```

**Comment by larsenv** [comment]
Yeah, I'm aware the Unix patcher is crap. Where can I send you the links to the wads?

**Comment by Apfel** [comment]
@larsenv you should fix your shit instead of telling us that you know that its shitty

**Comment by Alej0hio** [comment]
i dont think he uhh
wants to continiue making it
quite shit, cant even run on a raspberry pi so yes it sucks

**Comment by Apfel** [comment]
Mono on the Raspberry PI is community-maintained

**Comment by larsenv** [comment]
Yeah, per someone's request I removed the script from the latest release so people don't have to waste time with it. Cool to hear you got it working on Mac though.

**Comment by Bildcraft1** [comment]
Download the patched wads manually wihout the patcher

**Comment by KcrPL** [comment]
...or use the Windows version of the patcher.

**Comment by Apfel** [comment]
> Issue on Linux
>> Use the windows version
:clap:

**Comment by DarkPhoenix10** [comment]
:clap: make :clap: a :clap: working :clap: unix :clap: patcher :clap:

**Comment by Apfel** [comment]
👏

**Comment by larsenv** [comment]
Or you could improve it and make a PR.

**Comment by DarkPhoenix10** [comment]
okay

**Comment by Apfel** [comment]
Larsen how lazy are you

**Comment by KcrPL** [comment]
*KcrPL spent days and nights to polish the Windows patcher and you can't make MacOS/Linux patcher run*

![](https://media.tenor.com/images/af7a2ffee6abfdbcd053515b07eabf71/tenor.gif)

**Comment by Apfel** [comment]
*at least the batch version somewhat works, even if its bad sometimes*

**Comment by KcrPL** [comment]
*if it's bad, tell me what to fix lol*

**Comment by Apfel** [comment]
*some used tools are ew*
*real men use libWiiSharp directly :weSmart:*

**Comment by KcrPL** [comment]
no thanks

**Comment by Bildcraft1** [comment]
:+1:

**Comment by pablomancera** [comment]
Just tried the Linux/Mac .sh of RiiConnect24-Patcher-1.0.5 today on my Archlinux system and everything ran flawlessly, or I didn't receive any error in the console at least. I'll now install the wads on my wii.

PD: I felt very comfortable with the dialogs of the script, very kind haha

![captura de pantalla de 2019-01-17 15-38-49](https://user-images.githubusercontent.com/26395881/51347683-c37d3c00-1a6e-11e9-91b9-3d4385320397.png)

**Comment by larsenv** [comment]
Glad you got it working! I'd like to be able to fix the patcher so it works for others too.

**Comment by XxXTommyXxX** [comment]
ok, I think guys you can close it 😃

**Comment by odrevet** [comment]
nustool cannot be downloaded because $machine is not set. 
Replacing line 33 by 
case $unameOut in
fix the issu

**Comment by herb2k** [comment]
I got EVC patching to work on my mac... libgcrypt is a dependency that isn't downloaded: 

brew install libgcrypt

**Comment by herb2k** [comment]
Also, line 33 in the latest source had an error (was not present in an older source):

`case "$(unameOut)" in
    Linux*)     machine="linux";;
    Darwin*)    machine="mac";;
esac
` instead of 

`case "${unameOut}" in
    Linux*)     machine="linux";;
    Darwin*)    machine="mac";;
esac
`
