### ISSUE TITLE
Looks like powershell wasn't found on your pc

### ISSUE THREAD

**Issue by Nuxyer123** [RiiConnect24/RiiConnect24-Patcher#22]
OS:windows 7
version:1.0.5

**Comment by DarkPhoenix10** [comment]
thank you artuto very cool

**Comment by Nuxyer123** [comment]
> install powershell then

I have powershell...

**Comment by KcrPL** [comment]
Closing this issue. 

Turns out that sometimes you have to restart your PC or start the patcher as administrator.
Also, try using tools in the `Troubleshooting` menu.
