### ISSUE TITLE
Curl downloading never finishes

### ISSUE THREAD

**Issue by password12004** [RiiConnect24/RiiConnect24-Patcher#23]
On Windows, the curl never increases from 0.0 mb. The previous version stil works, though

**Comment by DarkPhoenix10** [comment]
kcrpl can you actually make a batch patcher that works smh

**Comment by KcrPL** [comment]
It's not a bug, it's his computer that refuses to run powershell. Can't really do anything about it. Try restarting your PC and trying again. No joke.
