### ISSUE TITLE
.bat file skips drive Q:

### ISSUE THREAD

**Issue by MrPeach2** [RiiConnect24/RiiConnect24-Patcher#24]
Which just happens to be where my SD card is. :(

**Comment by urmum-69** [comment]
So manually assigning the drive letter doesn't work? Could you elaborate?

**Comment by MrPeach2** [comment]
I just created an apps folder on my main data drive and rolled that way.
I was going to just add Q to the bat file, but this seemed to make as much sense.
However it then placed all the Wii files in the default dir of that drive (where RiiConnect.bat is), which was fine for my purposes, but could confuse someone else.

**Comment by MrPeach2** [comment]
Why would I change my drive mount scheme because of this? That makes no sense.

**Comment by KcrPL** [comment]
I exactly know why it won't detect Q drive.

I'm from Poland and in the entire Polish alphabet we don't have a single word that uses Q - so we don't have Q in our alphabet.

I forgot about Q when going through every letter. Sorry about that :P

Will fix that in next release. For now, manually assign the letter in the program.

**Comment by DarkPhoenix10** [comment]
silly kcrpl
