### ISSUE TITLE
JPN Channel Patching Support?

### ISSUE THREAD

**Issue by Givmin** [RiiConnect24/RiiConnect24-Patcher#28]

**Comment by Artuto** [comment]
Do we even support japan? O.o

**Comment by urmum-69** [comment]
Forecast and News both work for Japan

**Comment by InternalLoss** [comment]
We should support Japan; unlike most other channels, this won't even need localising since the only UGC is Mii's, aka names we don't need to translate. For contests this might change but we should probably support where possible.

**Comment by urmum-69** [comment]
Josh posted a wad for it, it's possible for sure. Guess this should be a feature in the next release for the patcher.

**Comment by InternalLoss** [comment]
I know it's possible, it's just someone needs to make the patch.

**Comment by KcrPL** [comment]
I'm planning to work on this soon.

**Comment by KcrPL** [comment]
Done in [402963c](https://github.com/RiiConnect24/RiiConnect24-Patcher/commit/402963cef62e5610dbc4672c61899f700d916223)
