### ISSUE TITLE
Remove WC24 Mail patches from IOS

### ISSUE THREAD

**Issue by InternalLoss** [RiiConnect24/RiiConnect24-Patcher#29]
We no longer need to patch the res check out of WC24 mail, so we should remove this patch from IOSPatcher - users don't need to update, but it'd make WiiConnect24 more IOS agnostic (we could change the patcher from using an XDELTA to simply finding the key in the /dev/kd driver, and changing it accordingly; this would allow for us to support more than just 31 and 80 in the future (think 60, 70; other system menu versions)

**Comment by larsenv** [comment]
I already did this.

**Comment by KcrPL** [comment]
The way how it just downloads the files from server allows us to silently update stuff without releasing a new release.

**Comment by InternalLoss** [comment]
Would’ve been nice for someone to say this was done ;P
