### ISSUE TITLE
Unable to Download.

### ISSUE THREAD

**Issue by IWantToScamBait** [RiiConnect24/RiiConnect24-Patcher#30]
Everytime I start the patch, it instsntly says it cannot download a file named "06-31.delta" with error code 1.

Am I doing something wrong? Is there a setting I have to change?

I am doing an express install straight to my SD Card.
I also turned off my Antivirus (Webroot Security Plus)

**Comment by KcrPL** [comment]
Check if the patcher can save to a location where the patcher is. Try moving the patcher to your desktop and start it as an administrator and let me know if it works or not.

**Comment by IWantToScamBait** [comment]
That done it. Thank you for the help.

-Morgon

**Comment by KcrPL** [comment]
You're welcome ;)

Can you also try putting the patcher in the location where it previously was and try running it as an administrator? Tell me if it worked.

**Comment by IWantToScamBait** [comment]
I ran it in administrator previously before moving it out of my Downloads folder. It did not work. However, I will try again.

**Comment by IWantToScamBait** [comment]
Hmm... Strange. It works now... Oh well! It works and that is what matters.
Thank you!
-Morgon

**Comment by KcrPL** [comment]
Thank you too ;)

Cheers.
