### ISSUE TITLE
RiiConnect Patcher crashes on custom install attempt after update from v1.1.1 to v1.1.2

### ISSUE THREAD

**Issue by TheShadowEevee** [RiiConnect24/RiiConnect24-Patcher#33]
Whenever updating the patcher from version 1.1.1 through the built in updater, it downloads 1.1.2 as expected. This file appears to be corrupt though as it is smaller then the file on github by like 3 kilobytes and crashes when trying to run a custom install.

Replication Steps:
Download and run v 1.1.1 from github (Most users would still have this version)
After the update press 1 for start
Wait for update checking and press 1 for riiconnect24 installation
Press 2 for custom installation
Crash

This is not present when downloading v1.1.2 from github, only when updating through built-in updater in v1.1.1 (And maybe others? Only tested v1.1.1)

**Comment by urmum-69** [comment]
How are you sure that it is corrupt?

**Comment by TheShadowEevee** [comment]
Well, I guess corrupt isn't the best term, but after downloading it multiple times it always turns up with the same issue and is 3kb lower in size then github release

**Comment by TheShadowEevee** [comment]
This is the file I get everytime I run the auto-updater from v1.1.1 for anyone who needs it. ([Here](https://cdn.discordapp.com/attachments/288361557044494337/658816112884056085/RiiConnect24Patcher_From_Built-in_Auto_Update.bat))

Sha256 of auto-updated file is effdceac277112af033bc2e4000e40c641dd729e55afa18ba9a514626e3c5f25

Sha256 of file from github is 43b0b480b5751ab1d1c9e41d5603f1a3e0a20b6e3badffc6b7db07115f839bf6

**Comment by KcrPL** [comment]
I'm aware of this issue. Noticed it when releasing v1.1.2 and this isn't my fault.

Basically, when curl downloads the file from the server, it saves it with LF coding (for Linux), not CR LF (for Windows). The file appears corrupted but working. [`And the difference between LF and CR LF is how lines are ended which makes the script crash.`].

I'm thinking about some kind of solution...
Probably just gonna make the patcher download a ZIP file and unpack it. It'll work the same way, it will just break older versions.

I need to think about something clever - give me some time.

**Comment by KcrPL** [comment]
Done. Set .gitattributes to not convert .bat from CR LF to LF. Now it's CR LF - give it a try now.

**Comment by TheShadowEevee** [comment]
I tried the auto-updating again in version 1.1.1 and 1.1.2 to 1.1.2.1, and both seem to still be showing the crashing effect after auto-updating when trying to run a custom install, along with the new Wii Mod Lite issue, which seems to also be a side effect of this.
