### ISSUE TITLE
Fails to download wii mod lite on both express and custom install

### ISSUE THREAD

**Issue by Jury76** [RiiConnect24/RiiConnect24-Patcher#34]
alright, so on windows 10, i updated from 1.1.2 to 1.1.2.1 via the patcher itself.
when i use the patcher, i get error code 1 and it says failing module "Downloading Wii Mod Lite". It also seems to fail at 26%

**Comment by urmum-69** [comment]
Can you elaborate, is there any specific error you're talking about? This on its own is not very descriptive and useless.

**Comment by Jury76** [comment]
I updated the description

**Comment by Jury76** [comment]
Also, i did follow the tip correctly and turned off my antivirus

**Comment by KcrPL** [comment]
Can you attach the file that you're using? (`the RiiConnect24 Patcher.bat`)

**Comment by m0thercomputer** [comment]
I've been experiencing the same error today while running the installer. If there's no further comment from the author, I can attach the batch file I'm using.

**Comment by TheShadowEevee** [comment]
I just ran a comparison of the patcher, one auto-updated, (Left in picture) and one directly downloaded from Github (Right in picture). The one from github continues while the auto-updated one stops. This leads me to believe this is a byproduct of issue #33 due to the way curl is downloading the files.

**Comment by Jury76** [comment]
Here's my RiiConnect24Patcher if any of y'all still need it.
[RiiConnect24Patcher.zip](https://github.com/RiiConnect24/RiiConnect24-Patcher/files/3999060/RiiConnect24Patcher.zip)

**Comment by KcrPL** [comment]
@Jury76 Well, yours is coded in LF, not CR LF...

I need to see if GitHub still hosts the files in LF and not CR LF

**Comment by KcrPL** [comment]
Fixed in [3dfec76](https://github.com/KcrPL/KcrPL.github.io/commit/3dfec767cda5a508718b9ade41f2fb63e63e480f)

I came back to an old way of accessing the repository. Turns out I'm gonna use it now...
