### ISSUE TITLE
are big size changes normal?

### ISSUE THREAD

**Issue by yepyepyep4711** [RiiConnect24/RiiConnect24-Patcher#39]
Hello,

I've used the patcher on three wbfs so far:
- Mario Kart RMCP01
- Wii Chess RTYP01
- Animal Crossing RUUP01

Patching took a lot longer for Mario Kart. I'm aware the process is different, but we're talking minutes vs seconds, is this expected?

My real question though is, Mario Kart didn't change size, but the other two did, big time. Like several hundreds of MB are now gone. What happened? Was something thrown away I might miss at some point ? If not, what was done?

Many thanks to everyone involved though, as I was able to play Mario Kart online today :)

**Comment by 2secslater** [comment]
I think you're making this issue on the wrong repo, and wrong place altogether.

Wiimmfi is separate from RiiConnect24.

Wiimmfi is an alternative to Nintendo Wi-Fi Connection,
whereas RiiConnect24 is an alternative to WiiConnect24.
both different services.

I think you should either ask on the [Wiimmfi Patcher](https://forum.wii-homebrew.com/index.php/Thread/51742-wiimmfi-Patcher/) thread, or on the [Wiimmfi Board](https://forum.wii-homebrew.com/index.php/Board/357-Wiimmfi-English/) of the Wii Homebrew forums.

**Comment by yepyepyep4711** [comment]
Why would the RiiConnect24-Patcher github be the "wrong place altogether" to ask about the behaviour of the RiiConnect24-Patcher? I can't follow you.

**Comment by 2secslater** [comment]
> Hello,
> 
> I've used the patcher on three wbfs so far:
> 
>     * Mario Kart RMCP01
> 
>     * Wii Chess RTYP01
> 
>     * Animal Crossing RUUP01

Here you mention using the patcher on three Wii disc titles.

The RiiConnect24 patcher does not patch games. Only certain Wii IOS titles, and the WiiConnect24 channels. Whatever patcher you're using, it's not the RiiConnect24 patcher.

**Comment by KcrPL** [comment]
@2secslater There's an option to patch games for Wiimmfi inside the patcher.

@yepyepyep4711 I think it all depends on the speed of your hard drive. Keep in mind that there are 2 patchers, one for only Mario Kart Wii, the other one for all games except MKWii.

Also, I think Wiimmfi patcher "scrubs" the image files - it deletes all "trash" data that's sometimes on your ISO image.

**Comment by yepyepyep4711** [comment]
> Also, I think Wiimmfi patcher "scrubs" the image files - it deletes all "trash" data that's sometimes on your ISO image.
That's what I thought. I think it's using wit to unpack and repack? But I was wondering how this differed from the process of making a wbfs file, which already is smaller than the iso. I mean, we're talking about either big savings in space or loss of a lot of content, which might be not needed in the first place but it's hard to judge without knowing what is is, you know?

**Comment by KcrPL** [comment]
Unfortunately, I did not make that tool and I don't know how exactly it works.

**Comment by Leseratte10** [comment]
The fact that the patching process takes a lot longer is normal. For games other than Mario Kart Wii, the patcher goes through the entire image once, and just replaces the server addresses from "nintendowifi.net" to "wiimmfi.de". 

For Mario Kart Wii, the entire image is extracted into the file system, then the server addresses are changed, some in-game texts changed from "Nintendo WFC" to "Wiimmfi", and the game patches for the Wiimmfi update system are installed. Then the whole image is repacked into a WBFS. 

Looking at the source code of the patchers, the Mario Kart Wii patcher copies the original image as-is without removing anything, the patcher for other games removes the UPDATE partition from the image. Wii games can contain System updates that are installed to the Wii at first start. These can be removed without problems from images as it's just a waste of space to have every single ISO contain the system updates if your Wii is up-to-date anyways. 

If you do want to keep all the updates for whatever reason, open the "patch-wiimmfi.bat" file and remove the `--psel=data` parameter, then the patcher shouldn't delete anything.

**Comment by KcrPL** [comment]
Right.

@Leseratte10 In the RiiConnect24 Patcher, there is an option to download and prepare both patchers for the user. Do you think it's worth adding an option to remove the `--psel=data` parameter? [Here's the script](https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/82447268dbe53b25d8ae5b0bc1625749f1ba2332/RiiConnect24Patcher.bat#L2403)

**Comment by Leseratte10** [comment]
I don't think that that's needed. I don't know of any game that would break with that parameter (so all the patched images should work just fine on Wiimmfi), and an additional option to remove that would probably just confuse the users. I think it's fine as it is, and if someone really wants to keep all the additional update data he could just edit the patcher file himself.

**Comment by KcrPL** [comment]
Sure, thx :)

**Comment by yepyepyep4711** [comment]
thanks for tall the answers everyone. That explains it.

@KcrPL @Leseratte10 There is only one reason I could figure to warn the user, and that would be if the resulting wbfs can't be turned back to an ISO and burnt to disc. AFAIK, the original wbfs is effectively a backup. You can take your disc, turn it into a wbfs for safekeeping or ease of use, and if at some point in time you need a disc again, turn it back to an ISO and burn it to disc.

Now, if deleting the update partition doesn't break this functionality, I agree there is no need to change anything. If it does, though, I think either warning the user ("the resulting file can't be used to burn a WII DVD") or offering a choice ("Do you want: 1 - smaller file, can't be turned back into a game disc anymore, or 2 - bigger file, keeps everything inside and can be turned back into a game disc") would be worth thinking about.

Cheers

**Comment by Leseratte10** [comment]
You can at any point take the resulting WBFS file, turn it back into an ISO and burn it onto a disc (of course that disc will be fakesigned then) and could play that on a Wii if A) your wii drive supports non-original discs, and B) you have a way to boot a fakesigned disc. The only thing that wouldn't work would be updating the Wii with that disc. 

So if you have a Wii with 4.1 for example that doesn't have IOS58 yet, because the Wii never got 4.3 and you didn't install IOS58 while installing homebrew, and you would then pick up a game that needs IOS58 (like "Your Shape"), and would try to run a burned disc with an ISO of Your Shape that has been patched with this patcher; *that* would fail. But I think it's highly unlikely that you'd burn a Wiimmfi-patched image of a game onto a disc, then find a Wii that can even read burned discs and then have that game require newer IOS than there are on the Wii. 

In that case, you'd have a problem and would need to either update the Wii over the internet, update the Wii using the original game disc, or homebrew the Wii. But a WBFS file with the update stuff removed can, generally, definitely be turned back into an ISO and into a working disc.

**Comment by yepyepyep4711** [comment]
Many thanks!
