### ISSUE TITLE
warning about image deletion

### ISSUE THREAD

**Issue by yepyepyep4711** [RiiConnect24/RiiConnect24-Patcher#40]
Hi all,

this is a simple end-user issue:
The script will delete the original wbfs I submit to it without warning. As a prudent person, I only gave it a copy, in case things go wrong at any point, but to prevent surprises, I'd like to suggest adding a warning somewhere, maybe on the screen where the script looks for ISOs and wbfs. Something like "this file will be modified and the original deleted. If you want to keep the original, make sure you made a copy before proceeding".

Cheers all and thanks for all the work. Stay safe

**Comment by KcrPL** [comment]
Hey,

Even better - I can add an option for it to make a copy of the original file. Are you interrested in that?

**Comment by yepyepyep4711** [comment]
yup, any of these is fine! Just something to prevent people from inadvertently "getting rid" of their original files ;)

Thanks

**Comment by KcrPL** [comment]
👍
Will be there in the next update :)

**Comment by yepyepyep4711** [comment]
Lovely
