### ISSUE TITLE
stop or log on error?

### ISSUE THREAD

**Issue by yepyepyep4711** [RiiConnect24/RiiConnect24-Patcher#42]
hi, the following happened today.
I tried to patch Guitar Hero - World Tour [SXAP52]. For some reason it was not in one wbfs file, but in one SXAP52.wbfs plus one SXAP52.wbf1. The patcher looked at first as it would be working, but in the end some red text flashed over the screen before the script went back to the starting screen. If I hadn't been staring at the screen, I'd have missed it. The end result was that SXAP52.wbf1 was still in the root folder, SXAP52.wbfs was gone completely (also not under (wiimfi-images), and I couldn't check what the problem was.

So I'd like to suggest for the script to pause or log output on error, or any other mechanism that would make it possible for the user to understand, and possibly fix, what didn't work.

Cheers

**Comment by KcrPL** [comment]
Hey,

Hmm... I don't know if Wiimmfi Patcher works with split files. 
But I'll look into ways of detecting errors because it's not checking for errors at all right now.

**Comment by urmum-69** [comment]
> Hey,
> 
> Hmm... I don't know if Wiimmfi Patcher works with split files.
> But I'll look into ways of detecting errors because it's not checking for errors at all right now.

The Wiimmfi patcher is just wit, it can handle split files fine
