### ISSUE TITLE
failing module Sharpii.exe

### ISSUE THREAD

**Issue by mattjburk** [RiiConnect24/RiiConnect24-Patcher#43]
/---\   ERROR.
  /     \  There was an error while patching.
 /   !   \ Error Code: -532459699
 --------- Failing module: Sharpii.exe / 31

TIP: Consider turning off your antivirus temporarily.
SOLUTION: Please check your internet connection.
      Press any key to return to main menu.
---------------------------------------------------------------------------------------------------------------------------

**Comment by TheShadowEevee** [comment]
Error's like these happen sometimes. It is best to get help in the #support channel on the [RiiConnect24 Discord Server](https://discord.gg/b4Y7jfD) (You can create a Discord account if you don't have one) or the less recommended, slower option is emailing support@riiconnect24.net.

**Comment by mattjburk** [comment]
OK. Will check out Discord Server. Thanks.
