### ISSUE TITLE
Forecast (Europe/Spain) Doesn't work

### ISSUE THREAD

**Issue by Ramshu** [RiiConnect24/RiiConnect24-Patcher#44]
When launching the forecast channel, it gives the following error:
The latest information could not be downloaded.
Error: FORE000006
[sysCheck.txt](https://github.com/RiiConnect24/RiiConnect24-Patcher/files/4515692/sysCheck.txt)

**Comment by 2secslater** [comment]
Hi, please try performing the battery fix at [wii.guide/riiconnect24-batteryfix](https://wii.guide/riiconnect24-batteryfix)

Furthermore, this issues page is for issues regarding the patcher ;)
Issues regarding the service should be brought to attention via email or on the RC24 Discord server (links to both are in this repository's `README.md`).

**Comment by Ramshu** [comment]
> 
> 
> Hi, please try performing the battery fix at [wii.guide/riiconnect24-batteryfix](https://wii.guide/riiconnect24-batteryfix)
> 
> Furthermore, this issues page is for issues regarding the patcher ;)
> Issues regarding the service should be brought to attention via email or on the RC24 Discord server (links to both are in this repository's `README.md`).

It worked, but now the news channel gives me the error, which before the battery fix worked well ...
Error: NEWS000006

**Comment by urmum-69** [comment]
This is not the place to discuss this. Email support@riiconnect24.net or join the discord server at https://discord.gg/b4Y7jfD
