### ISSUE TITLE
The News Channel has an alternate slide show song that plays as "might".

### ISSUE THREAD

**Issue by SomeUserOnTheInternet** [RiiConnect24/RiiConnect24-Patcher#45]
![dddd](https://user-images.githubusercontent.com/64291306/80266140-052c6780-8660-11ea-9b2b-a487b50b08ef.PNG)

**Comment by KcrPL** [comment]
Good catch :))

**Comment by KcrPL** [comment]
Closing, I'll put it manually because I'm currently working on an update.
