### ISSUE TITLE
Won't install VVC Files

### ISSUE THREAD

**Issue by JerrisonGamerYT** [RiiConnect24/RiiConnect24-Patcher#49]
Hi, I was trying to get this working but it won't download vvc files, I did the process like so but it just wont work please help

**Comment by JerrisonGamerYT** [comment]
And btw I was using dolphin

**Comment by Artuto** [comment]
What even is a VVC file

**Comment by KcrPL** [comment]
Can you please clarify what you mean?

**Comment by larsenv** [comment]
I think he might mean VFF files.

**Comment by JerrisonGamerYT** [comment]
Wait, it windows defender
