### ISSUE TITLE
Failing module: move.exe / 74

### ISSUE THREAD

**Issue by Kevingaming234** [RiiConnect24/RiiConnect24-Patcher#50]
I am using Virtual Box Running Windows 8.1. So I turned on net frameworks I made sure that I had the current version of the patcher. It worked fine up until it reached around 70ish percent and then an error shows up with the following
"ERROR There was an error while patching. Failing Module: move.exe / 74".
And a tip shows up saying turn off your antivirus temporarily even though I don't have one on. I don't know if Im missing something. Please let me know. Thanks.

**Comment by urmum-69** [comment]
Hey,
we now provide an image with windows PE you can boot for the patcher
it is linked on https://wii.guide/riiconnect24
try that instead, and mention if it works

**Comment by Kevingaming234** [comment]
It didn't go well since 1) I don't have an Ethernet cable around and 2) my computer doesn't have enough ram or power to run the image. It was able to load but it's just way too slow. Sorry. I could just wait longer or get an Ethernet cable.

**Comment by KcrPL** [comment]
Hey, alright - what region were you patching?

**Comment by Kevingaming234** [comment]
USA

**Comment by KcrPL** [comment]
Can you try to boot the .ISO on your Virtual Machine and try to use it there while I'm working on a possible fix to this?

**Comment by KcrPL** [comment]
Remember that it requires at least 3GB of RAM.

**Comment by Kevingaming234** [comment]
Yeah see that was the problem on my end. My computer doesn't have enough ram. When I tried running the iso it would completely freeze my computer will it's trying to load the iso image.

**Comment by KcrPL** [comment]
Alright, give me some time while I'm working on a possible fix.

**Comment by KcrPL** [comment]
Can you please try running this? Tell me if it fixed the issue or not.

[RiiConnect24Patcher.zip](https://github.com/RiiConnect24/RiiConnect24-Patcher/files/5300467/RiiConnect24Patcher.zip)

**Comment by Kevingaming234** [comment]
Sadly no the same error showed up near  74% 
![image](https://user-images.githubusercontent.com/68489407/94588668-341fb880-0252-11eb-99d4-bb9dd4b0565e.jpeg)

**Comment by KcrPL** [comment]
I'll just try to install Windows 8.1 on my VM. Will get back to your later.

**Comment by KcrPL** [comment]
![image](https://user-images.githubusercontent.com/17184296/94597591-0d7f7300-028e-11eb-8f88-1bcf9a53c72c.png)

I cannot reproduce the error :(

However, we'll try to see what the tools output. Here's a modified version of the patcher, it will tell you when to make screenshots (should ask twice). Take the screenshots and upload them here.

[RiiConnect24Patcher.zip](https://github.com/RiiConnect24/RiiConnect24-Patcher/files/5300987/RiiConnect24Patcher.zip)

**Comment by Kevingaming234** [comment]
Here is what i was able to get.


![image](https://user-images.githubusercontent.com/68489407/94601351-5ec53d80-0261-11eb-80fc-5b4b4c3ad490.png)
![image](https://user-images.githubusercontent.com/68489407/94601378-6684e200-0261-11eb-8893-18a1821a0824.png)

**Comment by KcrPL** [comment]
![image](https://user-images.githubusercontent.com/17184296/94601803-4cb0c280-0294-11eb-8130-a7bf6b4aaa49.png)
Huh, it should look like this.

[Try to install this and try again](https://download.visualstudio.microsoft.com/download/pr/fd5d2eea-32b8-4814-b55e-28c83dd72d9c/952A0C6CB4A3DD14C3666EF05BB1982C5FF7F87B7103C2BA896354F00651E358/VC_redist.x64.exe)

**Comment by Kevingaming234** [comment]
It couldn't install
![image](https://user-images.githubusercontent.com/68489407/94604180-4c4d0300-0265-11eb-8b05-1162eddf0ea8.png)

**Comment by KcrPL** [comment]
I have so many questions...

It literally worked for me when I installed it.
Any chance you could get a Windows 10 VM?

**Comment by Kevingaming234** [comment]
I have tried but it was really slow and it kept restarting. I tried the 32-bit version because 64-bit  is too much for my computer to handle.

**Comment by KcrPL** [comment]
There indeed seems to be an issue on 32 bit based systems. Investigating.

**Comment by KcrPL** [comment]
Alright, try launching the patcher and if it prompts you to update to v1.3.0.5, do so.
Lemme know if it works now or not.

**Comment by Kevingaming234** [comment]
I got good news (sorta) and bad news. The good news is i was able to update the patcher to v1.3.0.5. The bad news is although it did made more progress an error occurred around 88%
 
![image](https://user-images.githubusercontent.com/68489407/94613780-20387e80-0273-11eb-9f08-3cc5d79f048d.png)

**Comment by KcrPL** [comment]
Alright, download another update - I'm sure it'll work now.

**Comment by Kevingaming234** [comment]
It worked successfully. Thank you.

**Comment by KcrPL** [comment]
Thank you so much and I'm sorry for the lengthy debugging process :)
