### ISSUE TITLE
vWii No Internet

### ISSUE THREAD

**Issue by wiiuhackerman** [RiiConnect24/RiiConnect24-Patcher#51]
I can install the RiiConnect24-Patcher and all the things because i'm used to hacking my wii, but when i load into like everyone votes, it says no internet connection.

**Comment by urmum-69** [comment]
Hi,
You should send an email to support@riiconnect24.net or join the discord server for support (https://discord.gg/b4Y7jfD)
This page is strictly for issues with the patcher itself, which this clearly isn't.

**Comment by KcrPL** [comment]
Not related to the patcher, closing.

Please contact us using one of the links mentioned above.
