### ISSUE TITLE
Dies at 37% - Sharpii.exe cannot be started

### ISSUE THREAD

**Issue by EricTurner3** [RiiConnect24/RiiConnect24-Patcher#52]
I have the latest .NET framework (4.8, & 3.5 & run & developer edition) and I even downloaded Sharpii.exe directly from GitHub and it works fine.

The Sharpii.exe in System32\NewsChannelPatcher is failing on my Windows 10. I have tried replacing it with the new one I downloaded straight from the source [here](https://github.com/mogzol/sharpii/releases) but when the script re-launches, it overwrites the Sharpii.

The other Sharpii.exe downloaded in other folders like NCPatcher or CMOCPatcher work fine. It is whatever is in that NewsChannelPatcher folder that is failing.

**Comment by KcrPL** [comment]
Hey,

Could you pleaae open Settings in the Main Menu and tell me what's your reporting ID? (Please do not change it for now).

**Comment by KcrPL** [comment]
I think I've found your automatic report on the server.

It clearly reports that .NET Framework isn't found or cannot be run. The patcher also reported that you are running Windows 10 so it's interresting that you have issues with .NET Framework...

Anyway, [try running this](https://www.microsoft.com/en-US/download/details.aspx?id=17851) and try disabling your antivirus - it can sometimes help.

**Comment by EricTurner3** [comment]
My reporting ID was W0u3Pg (sorry did not receive an email on your first reply).

This is what happens if I try to run the .NET Framework 4.0 installer:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/5173637/95588025-ddb03800-0a10-11eb-9488-807d66c7b3f9.png">


Here is my Installed Apps for .NET:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/5173637/95588158-0f290380-0a11-11eb-97df-55d54e3f10a3.png">

I only have Windows Defender, I have Real-time virus protection off and firewall completely off but it still happens:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5173637/95588403-6038f780-0a11-11eb-8789-38dff025149b.png">

**Comment by EricTurner3** [comment]
I believe part of the problem was running the .bat as admin, so the directory was being set to C:\Windows\System32. I modified the batch file to hardcode in the initial directory:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/5173637/95603981-0a6e4a80-0a25-11eb-96f1-3f9656a34d31.png">

After making this change, I no longer have issues with the Sharpii.exe, but it still stops at 39% saying it cannot move the News Channel.

You can see I am still running it as admin (same error without admin) so it should have the proper permissions:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/5173637/95604297-6df87800-0a25-11eb-8e95-4b94441d2e51.png">

My virus & threat protection is off:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/5173637/95604466-a39d6100-0a25-11eb-8e46-542fbf368821.png">

Firewall is off: 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/5173637/95604534-b9128b00-0a25-11eb-959a-bdd82f98d675.png">

And even SmartScreen is off: 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/5173637/95604559-c29bf300-0a25-11eb-82b4-a79b99f6818e.png">

**Comment by KcrPL** [comment]
Can you just put the .bat file in your desktop and run it from there? (Run the original one, not the modified one)

**Comment by EricTurner3** [comment]
Same issue:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/5173637/95605978-b1ec7c80-0a27-11eb-8fb6-15113ff96814.png">

**Comment by KcrPL** [comment]
That's interresting.

I cannot reproduce the error on my computer. Can you please try using the patcher on another PC?

**Comment by EricTurner3** [comment]
I just tried my other windows 10 laptop, built in SD card slot, identifier is KfgE5P, it fails at the same step.

**Comment by KcrPL** [comment]
One more thing, can you try selecting Wii as a target device and not Wii U? Tell me if it works or not.

**Comment by EricTurner3** [comment]
It does not: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5173637/95655634-c8054600-0ad6-11eb-9afe-a85f43bcc9b3.png">

**Comment by EricTurner3** [comment]
It might have something to do with the 0001000248414750v7.wad / 0001000248414745v7.wad and the unpacked-temp folder (?). I did a search for all three of those and could not find them here on the desktop or in the %APPDATA%/Roaming folder either. Maybe it's not downloading the file properly and thus there is nothing for it to run the Sharpii.exe command on? Even if I try to do custom and just skip the news channel, it still tries to patch it and fails.

Root (No unpacked-temp folder):
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/5173637/95656488-c3439080-0adc-11eb-914d-6c050864139e.png">


NewsChannelPatcher Folder:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5173637/95656554-2a614500-0add-11eb-9371-850754b7da95.png">

WAD Folder: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/5173637/95656563-3947f780-0add-11eb-9bb6-05772c80822a.png">

**Comment by EricTurner3** [comment]
I also joined the RiiConnect24 Discord and posted in the #support channel, if that is easier than the back and forth on this GitHub issue.

**Comment by EricTurner3** [comment]
Issue was on my side, I was forgot I was blocking critical Nintendo URLS in PiHole to prevent a Wii U update. Removing the filters allowed the script to proceed as it should:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/5173637/95658634-efb1d980-0ae9-11eb-8c55-bc80185d5fdc.png">

**Comment by KcrPL** [comment]
Welp, stuff happens :)
