### ISSUE TITLE
Multiple errors, downloading using Windows 7

### ISSUE THREAD

**Issue by neferazure** [RiiConnect24/RiiConnect24-Patcher#54]
First, it kept saying Sharpii wouldn't download. I downloaded the sharpii file manually from a different thread I saw on here; we got over that jump. Then, it wouldn't download the News Channel (kept saying error downloading news channel). Fine. I figure I don't really need it, so decided to skip downloading it when going through the prompts again. 

Now, it says error when downloading "USA DELTA / 6" . 

It goes back and forth with what error is what. 

First it says news channel won't download. 
Then it says Sharpii. 
Then, it says USA DELTA 6 something or other. In other words, if it's not one thing it's another. I saw where you have the RiiConnect24 mail patcher available to download in the Homebrew Browser. You should consider making this RiiConnect24 Patcher available in the browser as well. 

There should also be a way to manually download all the files yourself if the Patcher thing won't do it for you. If I could just somehow get all the files myself and just place them on the card myself, this might work better. I've tried using the batch downloader at least 100 times now and I cannot get it to work. When I remove one error, something else comes up. It's frustrating. I really want to get this to work. 

Please help. 

If this information matters, I'm in the US and trying to install the US version. My Wii is set to all region everything, so I figure it really shouldn't make a difference. But disclosing that in case it matters.

**Comment by neferazure** [comment]
Also, it suggests turning off antivirus software, but it's definitely off; I always have it off.

**Comment by KcrPL** [comment]
It's an app for Windows therefore, you cannot run it on your Wii (`and cannot be put on Homebrew Browser`).

Can you please open Settings in the Main Menu and tell me what is your reporting ID?

**Comment by neferazure** [comment]
Is showing as PUrELK

**Comment by neferazure** [comment]
Now, a new error. Failing Module: Downloading xdelta3.exe / 13 

It's always a new issue every time I try to run it through again. This was when trying to do the Express Download option. But I get errors whether I do the express or the custom. Doesn't seem to make much of a difference.

**Comment by KcrPL** [comment]
I see. It's reporting error code 56 on Curl. Curl is a library used to download files.

And this means:

``CURLE_RECV_ERROR (56)``
``Failure with receiving network data.``


Perhaps your network is unstable or you're having issues connecting to us. (https://patcher.rc24.xyz/)

**Comment by neferazure** [comment]
I was only getting that error when using my mobile connection. But when I use my Spectrum connection, that error is no more, but I still get other errors. Latest one is something about CEK. It changes almost every new try. 

My Spectrum Connection is very strong with all of its bars so it can't be the connection. Unless I need to be right by my modem. I'm in a 2 story home and the wifi modem is downstairs in the living room.

**Comment by KcrPL** [comment]
If the error code is 56, it has to be something with the connection. I can't control that.
