### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by mioakiyama1** [RiiConnect24/RiiConnect24-Patcher#56]
When I try to run the .bat on windows10 it says "windows defender protected your pc". This didn't happen in the earlier versions, and it wasn't that big of a deal but maybe you should say something about it on the download page so people aren't scared when they see it.

**Comment by KcrPL** [comment]
Windows automatically "blocks" .bat files downloaded from the Internet from running.
This is a safety measure because .bat files can easily break your Windows installation or do harmful things.

You can just press "More info" and run anyway.

Closing. I can't do anything about this.
