### ISSUE TITLE
Wad is not recognized

### ISSUE THREAD

**Issue by AlexSC42** [RiiConnect24/RiiConnect24-Patcher#57]
![Errorrr](https://user-images.githubusercontent.com/77027861/103708218-c03e2c00-4f75-11eb-8be4-89f9eb68118e.PNG)

I followed the directions and I put the game wad in the WiiWarePatcher Folder, but the WAD is not recognized. What am I doing wrong?

**Comment by Artuto** [comment]
Can you take a screenshot of the folder?

**Comment by KcrPL** [comment]
Do not put it in the `WiiWarePatcher` folder. Put it in the folder where RiiConnect24Patcher.bat is.

**Comment by AlexSC42** [comment]
I finally got it now thanks guys!
