### ISSUE TITLE
Why is NUS_Downloader_Decrypt.exe used?

### ISSUE THREAD

**Issue by HTV04** [RiiConnect24/RiiConnect24-Patcher#58]
I've been doing some digging through the RC24 Patcher and noticed something interesting when it gets to patching the EVC (this also applies to the CMOC and the NC if I recall correctly). The patcher tells Sharpii to download the encrypted version of the title, then uses `NUS_Downloader_Decrypt.exe` to decrypt the files using a copy of `cert.sys`.

However, I ran some tests and Sharpii seems to be able to decrypt the files and pack them back into a WAD. I also tested modifying one of the decrypted files, and it still packed. Why does the patcher do this instead of just using Sharpii, like with the IOSs and the Forecast and News Channels?

EVC patcher code: https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/master/RiiConnect24Patcher.bat#L8613

**Comment by KcrPL** [comment]
It's been some time since I added this code but If I recall correctly, there were some issues with it not working etc.

Soon, I'll be rewriting the patching code so I'll keep this in mind to test.

**Comment by HTV04** [comment]
Ok, sounds great!

**Comment by HTV04** [comment]
Sorry, I might have accidentally used the wrong title ID when testing. I just tried again, and now I'm getting a `Downloading Ticket Failed: The remote server returned an error: (404) Not Found.` error.

I'm trying to make a version of the patcher that works under Linux, and I'm trying to avoid Wine as a dependency at all costs. Are there any alternatives to the `NUS_Downloader_Decrypt.exe` tool?

**Comment by HTV04** [comment]
I think I know what I did wrong. Turns out, some of the Japanese versions of the channels might have their certificates stored in the NUS, so they can be downloaded and decrypted directly via Sharpii. This seems to be the case for the CMOC, but I haven't tested the other channels yet.
