### ISSUE TITLE
Patcher doesn't see memory correctly

### ISSUE THREAD

**Issue by bastiro03** [RiiConnect24/RiiConnect24-Patcher#59]
Overview: see title
Guide to reproduce: 
1. Start RiiConnect24Patcher.bat (Version 1.4.0.1)
2. Have your Wii SD card (in my case USB stick) detected by the program
3. Select "Start"
4. Select "Wii"
5. Select "Install RiiConnect24 on your Wii"
Expected results: The Menu to select the express or custom installation is shown
Actual results: The message:
---------------------------------------------------------------------------------------------------------------------------
   /---\   ERROR.
  /     \  There is not enough space on the disk to perform the operation.
 /   !   \ Please free up some space and try again.
 ---------
           Amount of free space required: 700MB

      Press any key to return to main menu.
---------------------------------------------------------------------------------------------------------------------------
is shown.

**Comment by KcrPL** [comment]
How much space left do you have then? :)

**Comment by KcrPL** [comment]
BTW, it checks for the space in the drive RiiConnect24 Patcher is on, not on your USB Drive.

**Comment by bastiro03** [comment]
My SSD is 500GB, with only half of the space being used.

**Comment by KcrPL** [comment]
Did it work on v1.4.0?

**Comment by bastiro03** [comment]
Yes, i literally tried a few minutes before 1.4.0.1 released.

**Comment by KcrPL** [comment]
Can you give this a try and tell me if it works?
[RiiConnect24Patcher.zip](https://github.com/RiiConnect24/RiiConnect24-Patcher/files/5808607/RiiConnect24Patcher.zip)

**Comment by bastiro03** [comment]
Tried it, no difference, meaning it is likely a problem on my part.

**Comment by KcrPL** [comment]
Can you put the .bat file on your desktop and run it from there?

**Comment by KcrPL** [comment]
Alright, can you run cmd.exe and run this command?
`wmic logicaldisk where "DeviceID='C:'" get FreeSpace /format:value`

**Comment by KcrPL** [comment]
Fixed in [3d219ac](https://github.com/RiiConnect24/RiiConnect24-Patcher/commit/3d219ac427318f310a95995b69ec470052c60e54)
