### ISSUE TITLE
Patcher crashes after i clicked on it

### ISSUE THREAD

**Issue by Soan7** [RiiConnect24/RiiConnect24-Patcher#60]
it's not good, now I can't use riiconnect24 anymore

**Comment by KcrPL** [comment]
Can you give me more information about what's going on?

What Windows version are you on, what exactly happens, do you see something on screen etc.

**Comment by KcrPL** [comment]
Closing.

**Comment by Soan7** [comment]
Windows 7

**Comment by KcrPL** [comment]
Does it crash on start?

**Comment by Soan7** [comment]
Yes

**Comment by KcrPL** [comment]
Is your system language French?

**Comment by Soan7** [comment]
Yes
