### ISSUE TITLE
Typo at line 908 in RiiConnect24Patcher.sh

### ISSUE THREAD

**Issue by IsakTheHacker** [RiiConnect24/RiiConnect24-Patcher#66]
I just looked at RiiConnect24Patcher.sh when I stumbled upon this typo at line 908:
`"Did you the RiiConnect24 logo was made by NeoRame, the same person who made the Wiimmfi logo?"`
(It is in the fun_facts array)

**Shouldn't it be:**
`"Did you` `know` `the RiiConnect24 logo was made by NeoRame, the same person who made the Wiimmfi logo?"`
**Or:**
`"Did you` `know that` `the RiiConnect24 logo was made by NeoRame, the same person who made the Wiimmfi logo?"`

**Comment by HTV04** [comment]
Whoops, I'll fix that. Thanks for letting us know.

**Comment by IsakTheHacker** [comment]
Great!

**Comment by KcrPL** [comment]
I need to fix this too.

**Comment by HTV04** [comment]
Fixed for the Unix script, but I don't think I should close this issue until KcrPL has fixed the typo on his script.

**Comment by SketchMaster2001** [comment]
Yes don't touch .bat or we will be eliminated

**Comment by HTV04** [comment]
KcrPL fix this issue so we can close this lol

**Comment by SketchMaster2001** [comment]
Polish man is sleeping forever

**Comment by KcrPL** [comment]
Fixed in 89652291a0137a64b41fb1d03b0248068c754725.

Closing.
