### ISSUE TITLE
rc24.sh: main menu loop freshing

### ISSUE THREAD

**Issue by eku** [RiiConnect24/RiiConnect24-Patcher#67]
The Linux patcher v1.1.1 clears the shell window to output the main menu. Instead of waiting for an input, the window is cleared again and the menu is output and so on - loop.

```
GNU bash, Version 5.0.17(1)-release (x86_64-redhat-linux-gnu)
```

**Comment by SketchMaster2001** [comment]
You probably downloaded the source code instead of the release. Use the release and we have a fix coming today for that problem

**Comment by SketchMaster2001** [comment]
Fixed
