### ISSUE TITLE
Patched IOS breaks EmuNand

### ISSUE THREAD

**Issue by eku** [RiiConnect24/RiiConnect24-Patcher#70]
I created an EmuNand for PAL and Systemmenu 4.3 with ModMii and use it with NEEK2O on a Wii. As soon as I installed the 'IOS80 (RiiConnect24).wad', the Wii no longer starts with the EmuNand. The screen just stays black.

**Comment by larsenv** [comment]
Hi,

Did you just create this emuNAND and are using it for the first time?

**Comment by eku** [comment]
No, I've been configuring and using it for a longer time.

**Comment by eku** [comment]
The same problem occures with 'IOS31 (RiiConnect24).wad' which breaks the (patched) Weather Channel. There is something generally wrong with the patching under Linux.

**Comment by KcrPL** [comment]
Can you please test the patcher on Windows?

**Comment by eku** [comment]
I don't have Windows.

**Comment by SketchMaster2001** [comment]
Do you have Linux or macOS?

**Comment by KcrPL** [comment]
> I don't have Windows.

**_Any_** Windows computer in your house or anything?

**Comment by eku** [comment]
With respect. Do I have to apologise for only having access to Linux?

**Comment by KcrPL** [comment]
No, no, no. That's completely understandable 🙂

At this point, lemme just assume this issue is only on Linux.

**Comment by HTV04** [comment]
I sure hope this isn't, a potentially broken IOS80 would be a really big deal without BootMii (Priiloader wouldn't work, at least I don't think) 😬

I'll look into the issue. My Wii has BootMii, so this shouldn't be too hard to do some more testing on even if things go south.

However, I've looked at the Unix patcher code as well as the contents between the WADs generated by the Windows and Unix patcher, and they seem to be identical. Unless something's accidentally been changed in recent updates, I see no reason why the generated IOS31/IOS80 WADs wouldn't work.

**Comment by urmum-69** [comment]
> they seem to be identical
how did you determine this?
I seriously doubt it's a problem on the end of the patcher, more likely the emunand simply won't work for this purpose

**Comment by HTV04** [comment]
> how did you determine this?
By unpacking the WADs and comparing the total hashes of their contents (excluding the footer file, which will always be different depending on when the WAD was packed)

**Comment by SketchMaster2001** [comment]
> > At this point, lemme just assume this issue is only on Linux.
> 
> I sure hope this isn't, a potentially broken IOS80 would be a really big deal without BootMii (Priiloader wouldn't work, at least I don't think) 😬
> 
> I'll look into the issue. My Wii has BootMii, so this shouldn't be too hard to do some more testing on even if things go south.
> 
> However, I've looked at the Unix patcher code as well as the contents between the WADs generated by the Windows and Unix patcher, and they seem to be identical. Unless something's accidentally been changed in recent updates, I see no reason why the generated IOS31/IOS80 WADs wouldn't work.

I only changed the Wiimmfi code. We also download the IOS patches from the RC24 VPS so if the IOS is truly corrupted, we would have noticed already.

Closing due to the above

**Comment by eku** [comment]
Well, the patcher does not make any mistakes but the result does not work in EmuNand. But the unpatched IOS do. So the patch itself is toxic for the EmuNand? Can that be?
