### ISSUE TITLE
Error at end of patcher install on Mac

### ISSUE THREAD

**Issue by adkinsty** [RiiConnect24/RiiConnect24-Patcher#71]
I downloaded Unix version beta 1.1.1 and tried to install RiiConnect24 but at the end of installation it fails. My OS is Big Sur 11.2.1.

```
curl: (6) Could not resolve host: SD

Unix RiiConnect24 Patcher v1.1.0 beta
By HTV04 and SketchMaster2001

====ERROR=======================================================================

An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o ${2} -S -s 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher/v1/${1}
	* Line: 47
	* Exit code: 23
```

**Comment by SketchMaster2001** [comment]
Could you try installing the tools manually? (By going to `custom` and toggling only `6`. Also, do you have a SD Card named SD?

**Comment by adkinsty** [comment]
Yea I can try installing manually. And my SD card is named `WII SD`.

**Comment by SketchMaster2001** [comment]
Very confusing as the name shouldn't even touch the function

**Comment by adkinsty** [comment]
This is the output when I install Utilities only (option 6): 

```
Unix RiiConnect24 Patcher v1.1.0 beta
By HTV04 and SketchMaster2001

====Complete====================================================================

rc24.sh has succesfully completed the requested operation.

Output has been saved to "rc24output.txt," in case you need it.

Press any key to return to the main menu.
```

**Comment by SketchMaster2001** [comment]
It worked then, absolutely weird. Did anything install when you pressed express?

**Comment by adkinsty** [comment]
I actually I do recall the `rc24.sh-Files` folder appearing in my Downloads, but I tossed it because of the error. Maybe it actually installed the first time, despite the error. I'll try again.

**Comment by HTV04** [comment]
@adkinsty This might be an issue with the patcher, because I don't recall if took into account the spaces on volume names, oops. Try renaming your SD card to something without a space and seeing if it works.

**Comment by adkinsty** [comment]
Ok I'll replace with underscore. Btw, this is what the `rc24.sh-Files` folder in my downloads looks like after express installation (and the error shown above): 

<img width="576" alt="image" src="https://user-images.githubusercontent.com/15933204/109745842-743ceb80-7ba2-11eb-9b0e-a205d6807477.png">

**Comment by adkinsty** [comment]
It worked after changing the volume name. Thanks! 

```
Unix RiiConnect24 Patcher v1.1.0 beta
By HTV04 and SketchMaster2001

====Complete====================================================================

rc24.sh has succesfully completed the requested operation.

Output has been saved to "rc24output.txt," in case you need it.
```

**Comment by HTV04** [comment]
Hooray! And also oh no! I need to fix this LOL

**Comment by adkinsty** [comment]
Haha, hopefully won't be too difficult, I also should have known better not to use spaces in any names 😛

**Comment by HTV04** [comment]
Fixed 😜

And also no worries, it isn't bad to have spaces in volume names, or any folders, for that matter. It's usually the fault of the developer when errors occur because of that.
