### ISSUE TITLE
curl Error when I start patching (this is unix latest beta)

### ISSUE THREAD

**Issue by IsTheWit** [RiiConnect24/RiiConnect24-Patcher#73]
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

An error has occurred.

ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher/v1/${1}
	* Line: 47
	* Exit code: 35

**Comment by TheShadowEevee** [comment]
Are you using the latest version of the Linux Patcher? There was a update that was supposed to fix a similar issue a week ago. Please delete any existing version of the patcher, redownload it, and try again and see if that works.

Latest Release can be found at [This Repo's Releases Page](https://github.com/RiiConnect24/RiiConnect24-Patcher/releases/latest)

**Comment by IsTheWit** [comment]
Yes I am, and i have redownloaded it.

**Comment by IsTheWit** [comment]
Oh, and the same error happened

**Comment by IsTheWit** [comment]
I made a VM

**Comment by IsTheWit** [comment]
Closing.

**Comment by SketchMaster2001** [comment]
I added the fix for SSL errors a while back, it should not be doing that unless you are on an earlier version.
