### ISSUE TITLE
Crashing when starting the patcher

### ISSUE THREAD

**Issue by CrashedLife** [RiiConnect24/RiiConnect24-Patcher#74]
OS: Windows 10

When I open the patcher and enter 1 it'll automatically closes the patcher.
I've tried the latest version and some other versions.
Tried as adminstrator and as normal user.

**Comment by KcrPL** [comment]
Hey, is the language of your Windows French?

**Comment by CrashedLife** [comment]
No, it's German. 
I've tried to download the fix and it's showed that i didn't have a internet connection or curl is blocked in the firewall.

I've disabled my Pi-Hole and checked but curl isn't blocked.

**Comment by CrashedLife** [comment]
If you need it this is my error reporting identifier KDaxnw
