### ISSUE TITLE
Detected as Malware by Avast Free Antivirus

### ISSUE THREAD

**Issue by NERDBUG96** [RiiConnect24/RiiConnect24-Patcher#75]
Screenshot: https://drive.google.com/file/d/1RIJRe5z3QT4eTMkkcV_mlUgpst6DK_Hy/view?usp=sharing
Hello,
I attempted to run the RiiConnect24 patcher to patch the dolphin emulator on my PC.  I had used the patcher the day before and successfully patched a hardware Wii console.  When I tried to use the patcher it crashed, disappeared from the directory where it was located, and then Avast popped up claiming it was malware.  I don't know if this is a false positive or if this patcher is the victim of a poisoning attempt or something.  I guess I'll just wait on patching it for now.
Thank You.

**Comment by Artuto** [comment]
False positive. (for your own good you shouldn't be using Avast, btw)
