### ISSUE TITLE
Kaspersky False-positive

### ISSUE THREAD

**Issue by papercore-dev** [RiiConnect24/RiiConnect24-Patcher#79]
When I try to download this patcher, Kaspersky just prevents me and disables me to go further.

**Comment by TheShadowEevee** [comment]
Anti-Virus have false positives all the time. There's very little that can be done to change this patcher-side. Just mark it a false positive or disable Kaspersky temporarily. The source is viewable here on Github and easily using a text editor so you can confirm yourself there's nothing suspicious about the program.

I'm closing this, although if you have any other issues related to this feel free to leave a comment and reopen the issue.

**Comment by KcrPL** [comment]
Kaspersky always gets crazy about .bat files.

**Comment by TheShadowEevee** [comment]
I reported the false positive to Kaspersky and I got a response saying they would fix it. Hopefully this will help endure this doesn't happen again in the future.
