### ISSUE TITLE
Crashing on 32 bit Windows / User Reported Error

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/RiiConnect24-Patcher#8]
Like user reported, Windows gives an error about "`This app can't run on your PC`" when it hits 29% which is running `IOSPatcher/Sharpii.exe`. After me testing, turns out that every executable is compiled to 32 bit which means that it should run ok both on 32 bit and 64 bit OS's. I will be able to check it on virtual machine when I'm home which will be in few days. Anyway, any help with checking if it works would be appreciated.

![Screenshot](https://cdn.discordapp.com/attachments/288361557044494337/474649567330041866/Screenshot_263.png)

*If you happen to see if it works or not, send a screenshot here with the patched files and system info visible. Thanks :)*

**Comment by InternalLoss** [comment]
Will check now, but the fact screenshotted has missed out an important detail; "..thunder isn't common in Japan, and before this happened, the Japanese team didn't understand why they needed a thunderstorm icon"

[Source](http://weathernews.com/press/061226.html)

**Comment by InternalLoss** [comment]
Using a Windows 7 Thinkpad T61 on 32-bit Ultimate, I can easily surpass 29%, and completed the whole thing.

**Comment by KcrPL** [comment]
I see. I will also try it home and see if it finishes.

Thanks :)

**Comment by Alej0hio** [comment]
dude its morning can you fricking wait before you help someone

**Comment by InternalLoss** [comment]
@Alej0hio I don’t seem to get your point; if it’s morning surely I should have a try and see if I can reproduce issues?

No point sitting here doing nothing.

**Comment by KcrPL** [comment]
I don't get your point, Alej. Saying eat breakfast and brush your teeth is not a really great thing to say on the internet especially when everyone lives in different timezones and also remember that as a rc24 dev I'm trying to be online at all times and do actual stuff and any help is appreciated. 

I'm deleting your comments.

**Comment by Alej0hio** [comment]
Thats fine. Also, some tine (i dont remember) my antivirus deleted sharpii, but luckily rc24 patcher downloaded it

**Comment by KcrPL** [comment]
Yeah, some (bad) antiviruses detect Sharpii as a virus.

**Comment by Alej0hio** [comment]
My dad forces me to have Norton, so 99% of stuff i download actually needs to be recovered (most of them are of "ws.reputation" which is just because almost no one downloaded it, and when i whitelist the apps my pc isnt dead

**Comment by ApfelTV** [comment]
i will decompile Sharpii and check its build config

**Comment by ApfelTV** [comment]
and does the issue exist on Linux/Mac machines as well?

**Comment by Alej0hio** [comment]
Probably not @ApfelTV 32-bit linux is common

**Comment by KcrPL** [comment]
Closing as it looks like everything works fine on 32 bit Windows.

**Comment by ApfelTV** [comment]
Good to know that this thing got fixed just by building Sharpii for x86 as well.

**Comment by Artuto** [comment]
*get flagged*

**Comment by ApfelTV** [comment]
wow youre funny boi

**Comment by Alej0hio** [comment]
this thread is cancer

**Comment by InternalLoss** [comment]
Locking this thread; can you all please actually leave comments that are relevant, and not random bull please? Otherwise, I guess we'll have to issue GitHub blocks...

**Comment by KcrPL** [comment]
...was about to block it.
thx
