### ISSUE TITLE
xdelta3 error in RiiConnect24Patcher.sh

### ISSUE THREAD

**Issue by Kerrnel** [RiiConnect24/RiiConnect24-Patcher#83]
(Using default / recommended path)

....

Unix RiiConnect24 Patcher v1.1.2 beta
By HTV04 and SketchMaster2001

Now patching. This may take a few minutes, depending on your internet speed.

 X System Patches
 X Forecast and News Channels
  Check Mii Out/Mii Contest Channel
  Everybody Votes Channel
  Nintendo Channel

xdelta3: unavailable secondary compressor: LZMA: XD3_INTERNAL

Unix RiiConnect24 Patcher v1.1.2 beta
By HTV04 and SketchMaster2001

An error has occurred.

ERROR DETAILS:
        * Task: 
        * Command: xdelta3 -d -f -s Temp/Working/${1}/${4}.app Temp/Files/Patcher/${1}/${region}/${4}.delta Temp/Working/${1}/${4}_patched.app
        * Line: 95
        * Exit code: 1

Open an issue on [ here ]

**Comment by SketchMaster2001** [comment]
This seems to be an issue with your xdelta binary, try updating it with your package manager or reinstall it if already up to date.

**Comment by TheShadowEevee** [comment]
There's been no response to this for 2 and a half weeks, and since it seems to be an issue with the users machine I'm going to close it. Feel free to reopen it if the issue persists, instead of creating a new issue.

**Comment by RockfordRoe** [comment]
I had this error as well on gentoo, and what solved it was adding the `lzma` flag to `dev-util/xdelta`
