### ISSUE TITLE
RiiConnect24 taking longer than it should for patching

### ISSUE THREAD

**Issue by lordmenace** [RiiConnect24/RiiConnect24-Patcher#85]
So I've been staring at my computer with the riiconnect24 patcher running for over 3 days and i'm tired from it and i keep getting these errors
![not working](https://user-images.githubusercontent.com/83987571/124143038-6617b280-da50-11eb-92ae-711bfd17bd12.PNG)
and all my antiviruses are disabled, 
![NOTWORKING_AGAIN](https://user-images.githubusercontent.com/83987571/124143325-a70fc700-da50-11eb-9886-d9e03501d4fd.PNG)
and this one too

**Comment by KcrPL** [comment]
Can you please go to settings in the main menu and tell me what's your random generated ID?

**Comment by lordmenace** [comment]
![RiiConnect24 Patcher idenifyer](https://user-images.githubusercontent.com/83987571/124312703-5e7e0980-db35-11eb-9059-a31ac6fcc7a5.PNG)
here is my id

**Comment by KcrPL** [comment]
Alright, I checked most of the error reports sent by your ID, I see a lot of cURL issues and Sharpii errors.
Also, you're on an old version of Windows 10 (1703, from 2017!) so I'm not sure if that's an issue but I suggest updating.

Anyway, perhaps you have unstable Internet connection? Maybe put the patcher on your desktop and run it from there.

**Comment by lordmenace** [comment]
Ok i will try that thanks!

**Comment by KcrPL** [comment]
No response, closing.
