### ISSUE TITLE
Stuck in choose country loop

### ISSUE THREAD

**Issue by CatMow** [RiiConnect24/RiiConnect24-Patcher#90]
Please help.

https://user-images.githubusercontent.com/84914492/128626211-8a79115e-01c6-4f17-87b7-e73854e36fc7.mp4

Check in video above. Pls help ASAP!

**Comment by KcrPL** [comment]
You're supposed to type in a number near your selection. So if you want Europe, type 1. USA, type 2 etc.

Not an issue, closing. However I might add an option to use letters for selection.
