### ISSUE TITLE
"An error has occurred." Terminal, Macintosh

### ISSUE THREAD

**Issue by taviol** [RiiConnect24/RiiConnect24-Patcher#92]
"
ERROR DETAILS:
	* Task: 
	* Command: mkdir -p "${out_path}/WAD"
	* Line: 673
	* Exit code: 1
"

**Comment by TheShadowEevee** [comment]
Please change the directory you are running the patcher from. It is likely you don't have some permissions in that folder. Try moving the patcher to your Desktop and running Terminal from there as well.
