### ISSUE TITLE
Patcher crashes on Linux system

### ISSUE THREAD

**Issue by crystalstorm466** [RiiConnect24/RiiConnect24-Patcher#93]
Tried to launch RiiConnect24 with `bash ./RiiConnect24.sh` and I get the following error:
`ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://sketchmaster2001.github.io/RC24_Patcher/${1}
	* Line: 43
	* Exit code: 127
`

**Comment by crystalstorm466** [comment]
Error fixed: Turns out I never had curl installed even though ubuntu should come with it.

**Comment by Peter0x44** [comment]
We already have a check for ncurses, there should probably be one for curl too

**Comment by Peter0x44** [comment]
https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/1a25213222235af457582573574ff27ff9aab146/RiiConnect24Patcher.sh#L1066
actually... there is one
I wonder why it didn't work here
