### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [RiiConnect24/RiiConnect24-Patcher#94]
I'm using the script for UNIX/Linux and when I run it says:

ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://sketchmaster2001.github.io/RC24_Patcher/${1}
	* Line: 43
	* Exit code: 6
![immagine](https://user-images.githubusercontent.com/89483522/134370558-4293e4ab-f846-4f21-9431-c3a68358a368.png)

Can anyone help me? 
Edit: don't know if makes a difference, but I'm running under Linux Mint 20.2.

**Comment by HTV04** [comment]
Do you have curl installed?

**Comment by whiteshield20205** [comment]
Yes, curl is installed.

**Comment by SketchMaster2001** [comment]
This makes no sense, curl error code 6 is `Couldn't resolve host.`

**Comment by whiteshield20205** [comment]
![IMG_20210923_080714](https://user-images.githubusercontent.com/89483522/134461275-077918f1-2c6b-41a0-8f6f-6509e5a34fcf.jpg)
It seems that this is the problem.

**Comment by SketchMaster2001** [comment]
`404` and `Couldn't resolve host` are two completely different things. Secondly, you only passed part of the URL, which does not exist. `https://sketchmaster2001.github.io/RC24_Patcher/${1}` Works by inserting a variable which is the file cURL needs to download. `https://sketchmaster2001.github.io/RC24_Patcher` will never exist.

**Comment by whiteshield20205** [comment]
Ew, I must have been distracted while I was writing the post. Anyways, do you have an idea of what could this error be?

**Comment by KcrPL** [comment]
Ghost account, closing.
