### ISSUE TITLE
Typo in UNIX patcher setup.sh

### ISSUE THREAD

**Issue by Pippadi** [RiiConnect24/RiiConnect24-Patcher#98]
I'm using the UNIX patcher from the Releases section on openSUSE Tumbleweed (Linux, 64-bit).
I am trying to patch my Mario Kart Wii WBFS. I've placed it in the same directory as `RiiConnect24Patcher.sh`, but it keeps telling me that it's not able to find the ISO/WBFS.
Just before that screen, however, I see curl errors flash past. I managed to modify the script so that I could get time to modify `rc24.sh-Files/patch-images.sh` and get a few more details. Here are the errors I see:
```
curl: (22) The requested URL returned error: 404
https://sketchmaster2001.github.io/RC24_Patcher/Wiimmfi-stuff/wit(linux-64)

chmod: cannot access 'wit': No such file or directory
curl: (22) The requested URL returned error: 404
https://sketchmaster2001.github.io/RC24_Patcher/Wiimmfi-stuff/wszst(linux-64)
```
Putting those URLs into a browser gives me 404 errors, but changing `(linux-64)` to `(linux-x64)` gives me a file to download, which I assume is what's being looked for. I believe the `sys` environment variable is set incorrectly in `rc24.sh-Files/bin/setup.sh`.

Could someone rectify this?
Thanks!

Edit: Fix malformed sentences.

**Comment by Lord-Giganticus** [comment]
Found the typo line: https://github.com/SketchMaster2001/sketchmaster2001.github.io/blob/0221a143ee92d6b3ba74f775b7f70605df550352/RC24_Patcher/Wiimmfi-stuff/bin/setup.sh#L93

**Comment by Pippadi** [comment]
Is that block of code setting `sys` even required in `setup.sh`, since it's already in `RiiConnect24Patcher.sh`?
[https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/master/RiiConnect24Patcher.sh#L1048](https://github.com/RiiConnect24/RiiConnect24-Patcher/blob/master/RiiConnect24Patcher.sh#L1048)

Also, is there a repo where `setup.sh` is hosted? I wouldn't mind trying to fix it myself and filing a pull request there.

**Comment by SketchMaster2001** [comment]
Should be fixed. Closing.
