### ISSUE TITLE
curl error: Line: 47, Exit Code 35. on Mac with UNIX Patcher

### ISSUE THREAD

**Issue by MaxTanner724** [RiiConnect24/RiiConnect24-Patcher#99]
so i have a problem where when the patcher started patching, it gave an error with line 47 and exit code 35. how do i fix it. PLEASE!

ERROR DETAILS:
	* Task: 
	* Command: curl --create-dirs -f -k -L -o "${2}" -S -s --insecure 
https://patcher.rc24.xyz/update/RiiConnect24-Patcher/v1/${1}
	* Line: 47
	* Exit code: 35

Open an issue on https://github.com/RiiConnect24/RiiConnect24-Patcher/issues 
regarding your error. Alternatively, contact either HTV04 #4802 or 
SketchMaster2001 #8837 on Discord.

**Comment by TheShadowEevee** [comment]
This is an SSL issue that should be resolved. If this is still occurring feel free to reopen this issue with new details.
